NatLibFi/Annif

- annif/annif.py
- tests/test_annif.py
A basic implementation for project administration commands. The `annif init` command also now checks for orphaned indexes and removes them if necessary.
> Implement project admin commands. Fixes #8

- .lgtm.yml
Hi, as discussed over on the LGTM forum: https://discuss.lgtm.com/t/mostly-python-project-detected-as-javascript/1335
> Add LGTM configuration excluding fasttext

- .travis.yml
- Pipfile
- setup.py
This should make it easier to install the package also without Pipenv.
Also removes python-coveralls dependency because it caused install problems with Pipenv, probably because it explicitly depends on coverage==4.0.3 and there are other dependencies which will accept a newer version.
> use fasttextmirror package from official PyPI instead of fasttext from test PyPI

- annif/backend/dummy.py
- annif/backend/fasttext.py
- annif/backend/http.py
- annif/backend/tfidf.py
- annif/eval.py
- annif/hit.py
- annif/util.py
- tests/conftest.py
- tests/test_backend.py
- tests/test_backend_fasttext.py
- tests/test_backend_http.py
- tests/test_eval.py
- tests/test_hit.py
> Issue188 lazy result conversion

- .travis.yml
The container-based Precise image we were using is no longer available, so it makes sense to switch to the most modern build environment available. We also get test on Python 3.7 which was previously difficult.
> Switch to Xenial build system in Travis; test on Python 3.7 too

- annif/project.py
- annif/swagger/annif.yaml
- projects.cfg.dist
- tests/projects.cfg
- tests/test_project.py
> Simplify project configuration by allowing only one backend per project

- annif/cli.py
- annif/eval.py
- annif/hit.py
- annif/rest.py
- tests/test_hit.py
> Speed up optimize command and avoid high memory usage

- annif/cli.py
> Fix (again) high memory usage in optimize command

- annif/cli.py
- annif/project.py
- annif/rest.py
- tests/projects.cfg
- tests/test_cli.py
- tests/test_project.py
- tests/test_rest.py
> Implement access levels for projects

- annif/eval.py
> Avoid returnin nan values for Precision@K

- annif/backend/vw_multi.py
- tests/test_backend_vw.py
So they don't confuse model loading. Without this fix, `annif eval` seems to hang.
> Move passes-related settings outside _create_params 

- annif/backend/fasttext.py
- annif/backend/mixins.py
- annif/backend/vw_multi.py
- tests/test_backend_vw_multi.py
Makes it possible to specify what inputs are used to build the VW model. Thus it's possible to use e.g. a well trained subject indexing algorithm as input to the vw classifier.
> vw-multi backend: use input from other projects

- annif/backend/backend.py
- annif/backend/fasttext.py
- annif/backend/pav.py
- annif/backend/tfidf.py
- annif/backend/vw_multi.py
- annif/datadir.py
- annif/project.py
- annif/vocab.py
This little refactoring introduces a DatadirMixin class that can be used by AnnifProject and AnnifVocabulary. Gets rid of the near-duplicate `_get_datadir` methods, hopefully silencing Code Climate complaints.
> Refactor: extract data directory handling into a mixin class

- annif/backend/fasttext.py
- annif/backend/vw_multi.py
- annif/cli.py
- annif/corpus/convert.py
- annif/corpus/document.py
- annif/corpus/subject.py
- annif/project.py
Issue #262 - Character encoding (Windows)
> Explicit character encoding for all calls to open()

- annif/backend/__init__.py
- annif/corpus/__init__.py
- setup.py
- tests/test_backend.py
- tests/test_cli.py
- tests/test_project.py
- tests/test_rest.py
Today I worked on a different project and decided to use `click` for the first time from scratch. Knowing Annif used it, I came right here to look for the `setup.py` to see what was there.
Only found `click-log` (interesting!), but not `click`. Then decided to look what other transitive dependencies were being used in the project.
I think the second commit covers all the dependencies used in code and tests. Added them to the respective groups of dependencies.
Cheers
Bruno
> Remove unused imports and declare dependencies used

- annif/rest.py
- annif/swagger/annif.yaml
- annif/templates/home.html
- tests/test_rest.py
Fixes #268
This changes the Swagger spec and related code. The web UI is also changed accordingly.
> Rename REST "analyze" method to "suggest"

- Pipfile
- annif/backend/pav.py
- annif/project.py
- setup.py
Following the documentation and noticed the following warning:
```
/home/kinow/Development/python/workspace/Annif/venv/lib/python3.7/site-packages/sklearn/externals/joblib/__init__.py:15: DeprecationWarning: sklearn.externals.joblib is deprecated in 0.21 and will be removed in 0.23. Please import this functionality directly from joblib, which can be installed with: pip install joblib. If this warning is raised when loading pickled models, you may need to re-serialize those models with scikit-learn 0.21+.
warnings.warn(msg, category=DeprecationWarning)
```
Not seen when running `pytest`.
> Fix warning for joblib in scikit

- annif/backend/backend.py
Was passing some functions with a debugger reading the code and noticed that here when the dict was not `None`, it could still be empty. And the `update` method was being called unnecessarily.
Won't cause any speed up, but still worth changing it I think?
> Avoid calling update with empty dicts

- annif/backend/vw_ensemble.py
- tests/test_backend_vw_ensemble.py
Related to #235 
This PR adds more features to the ML models built in the vw_ensemble backend:
* raw, descriptor invariant scores returned by the source project
* "zero features" whenever a source project returns a zero or near-zero score for a concept
* combinations (interactions) between raw scores
In my experiments, these additional features seem to give a small improvement in results.
> Add more features to the model in vw_ensemble

- .drone.yml
The previously used when clause applies only to individual steps of a pipeline
> Fix build to be triggered on push to master only

- annif/backend/vw_ensemble.py
- tests/test_backend_vw_ensemble.py
The additional features in vw_ensemble turned out to be a bad idea - they
introduce extra complexity without significantly improving results.
Reverting the merge for now. The vw_ensemble backend needs more work, but
it's better to have a simple version in master and build upon that.
Revert "Merge pull request #288 from NatLibFi/issue235-more-features"
This reverts commit 2ea1130aceeeb56926f728d416430e60a2c34633, reversing
changes made to 85216528dbcf2c07efe79aff0c9bb5185ba2f3f4.
> Revert PR #288 additional features for vw_ensemble

- docs/requirements.txt
Although the RTD build errors seemed already to be fixed by adding `.readthedocs.yml` (in #285), the errors still appeared (first in the stable version [build](https://readthedocs.org/projects/annif/builds/9330384/), then also in [latest](https://readthedocs.org/projects/annif/builds/9344263/). 
The errors seem to be related to capitalization of package names, the actual error is:
`error: The 'click' distribution was not found and is required by click-log, annif`
The same error raised also for `flask` (after trying to get pass the `click` error). 
See also the discussion in https://github.com/readthedocs/readthedocs.org/issues/4051
On my local machine a workaround for these is to add `flask` and `PyYAML` packages to the `requirements.txt`
> fix-RTD-build-error

- .drone.yml
When doing a release, a specific Docker image should now be build and tagged with the value from git tag (release version).
This closes #297.
> Issue297 set docker image tag from git tag

- .travis.yml
- Dockerfile
Vowpalwabbit version [`8.7.0.post1`](https://github.com/VowpalWabbit/vowpal_wabbit/releases/tag/8.7.0) was released 12.7.2019 in Pypi. It requires a few new dependencies to be installed, and change on the linking fix of libboost. The [VW wikipage](https://github.com/NatLibFi/Annif/wiki/Optional-features-and-dependencies) has been updated according to these.
However, issue #291 states VW should be pinned to 8.5. Is that still valid now when newer version is released (note that 8.6 is not in Pypi)?
> Use vw version 8.7

- .drone.yml
Previously drone built and published docker image to quay.io when a push was made to master branch. Thus if there was error in build, it was detected only after PR merge to `master`. 
This adds the `build` step to the drone pipeline, which is run when a push is made to any branch or PR, but does not publish the image to quay.io. Failed build should thus be detected before merging to `master`.
> Build but do not publish on pushes and PRs to all branches

- .drone.yml
Apparently even in dry-run build step there needs to be the same settings as in actual build-and-publish steps ([drone build errored](https://drone.kansalliskirjasto.fi/NatLibFi/Annif/120/1/2) with `Error parsing reference: ":latest" is not a valid repository/tag: invalid reference format`)
> Dry run of drone builds for p rs

- Dockerfile
Drone builds (e.g. https://drone.kansalliskirjasto.fi/NatLibFi/Annif/118/1/2) were failing with error:
```
Package libboost-python1.62.0 is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
E: Unable to locate package libboost-program-options1.62.0
E: Couldn't find any package by glob 'libboost-program-options1.62.0'
E: Couldn't find any package by regex 'libboost-program-options1.62.0'
E: Package 'libboost-python1.62.0' has no installation candidate
E: Unable to locate package libboost-system1.62.0
E: Couldn't find any package by glob 'libboost-system1.62.0'
E: Couldn't find any package by regex 'libboost-system1.62.0'
```
This (apparently) was due to that the base image …
> Pin base image to Debian Buster; update libboost version accordingly

- annif/corpus/convert.py
- annif/corpus/document.py
- annif/corpus/subject.py
- annif/corpus/types.py
- tests/test_corpus.py
Fixes #309
This PR modifies the document corpus processing code so that URIs are looked up based on labels and vice versa (with the help of a subject index). This should make it possible to use simple `.key` files with only subject labels, as [specified in the wiki](https://github.com/NatLibFi/Annif/wiki/Document-corpus-formats#simple-subject-file-format).
Marking as draft PR since some refactoring may be necessary before merging.
> Issue309 key files with labels only

- docker-compose.yml
In [the wiki section](https://github.com/NatLibFi/Annif/wiki/Usage-with-Docker#using-annif-with-gunicorn-nginx-and-maui-backend) for `docker-compose.yml` it was instructed to run command
```
ANNIF_PROJECTS=~/annif-projects UID=${UID} GID=${GID} docker-compose up
```
to start up the services, which set `UID` and `GID` variables which in turn were intended to be used for setting user in containers. However this was actually failing with the warning
```
bash: UID: readonly variable
WARNING: The UID variable is not set. Defaulting to a blank string.
```
and the user remained root in the containers. 
This is fixed by using different name than `UID` in the `docker-compose.yml` and the instruction in Wiki.
> Fix unsuccessful setting of readonly bash variable by using different name than UID

- annif/cli.py
- annif/project.py
- tests/test_cli.py
The `init` command simply deletes all files under `data/projects/project-to-remove/` (that directory will remain):
```
$ annif init tfidf-fi-copy 
Removed data files for project tfidf-fi-copy.
$ annif init nonexistent-project
No projects found with id 'nonexistent-project'.
```
Stated in the issue comment: "It could wipe all state and reset any configuration settings." 
Is this PR enough for this? 
The issue #269 for creating backend for using Maui server plans using `init` command for "creating tagger on the Maui server end", which is left for future.
This closes #251.
> Issue251 cli init command

- annif/default_config.py
- annif/project.py
- tests/projects.cfg
- tests/projects_invalid.cfg
- tests/test_project.py
Raise `ConfigurationException` instead of full traceback in following situations:
1. when trying to use (train/suggest) a project without a backend set in `projects.cfg`:
```
$ annif train nobackend -p tests/projects.cfg any_trainingdata.tsv 
Error: Project 'nobackend': backend setting is missing
```
This is in line with missing vocab error: ` "Error: Project 'maui-fi': vocab setting is missing"`.
2. when trying to use `projects.cfg` that has duplicated sections or entries:
```
$ annif train any_backend -p tests/projects_invalid.cfg any_trainingdata.tsv 
Error: Error: While reading from 'tests/projects_invalid.cfg' [line 10]: section 'duplicatedproject' already exists
```
This closes #282.
> Issue282 handling syntax errors in projects config

- annif/exception.py
- tests/test_exception.py
I realized that `AnnifException` isn't intended to be instantiated directly but doing so was still possible. This PR changes into an abstract base class, which cannot be instantiated.
While performing the change, I noticed that the prefix mechanism used to generate error messages was broken. This PR fixes it as well.
Example error before the changes:
Error: Project 'noanalyzer': vocab setting is missing
Example error after the changes:
Error: Misconfigured project 'noanalyzer': vocab setting is missing
> Turn AnnifException into an abstract base class and fix message prefix behavior

- .drone.yml
- Dockerfile-dev
The image intended for [development](https://github.com/NatLibFi/Annif/blob/master/Dockerfile-dev) (i.e. one including the installed [dev packages of Pipfile](https://github.com/NatLibFi/Annif/blob/master/Pipfile#L6) and pytest) was automatically build by drone and pushed to quay.io with the `dev` tag. However, that tag name could cause confusion (especially when tags with release versions will come to use).
This PR removes the drone step for building and publishing dev image, and the instructions in [Wiki for using docker for development](https://github.com/NatLibFi/Annif/wiki/Usage-with-Docker#using-docker-in-annif-development) is updated with instructions to manually build the image for development.
Also removes unnecessary full-access to everyone for source code in image.
> Do not push docker image with dev tag to quay.io

- annif/corpus/document.py
This is a follow-up for PR #263 which added explicit `encoding="utf-8"` parameters to many `open` calls but missed one case: when reading document corpora from TSV files (optionally gzip compressed). This PR fixes the one remaining case while also simplifying the code slightly.
The problem was reported by Pekka K. / Yle Arkisto. It manifests mostly on Windows, where non-UTF-8 locales (e.g. cp1252) are commonly used.
> Always use UTF-8 encoding when parsing TSV file document corpora

- pytest.ini
I've been having a warning on every pytest run (with the following related package version: pytest=5.0.1; pytest-cache=1.0; pytest-cov=2.7.1; pytest-flask=0.15.0; pytest-pep8=1.0.6; pytest-watch=4.2.0):
```
============================================================================================= warnings summary =============================================================================================
/home/jmminkin/.local/share/virtualenvs/Annif-b5vsMxU8/lib/python3.6/site-packages/_pytest/mark/structures.py:332
/home/jmminkin/.local/share/virtualenvs/Annif-b5vsMxU8/lib/python3.6/site-packages/_pytest/mark/structures.py:332: PytestUnknownMarkWarning: Unknown pytest.mark.pep8 - is this a typo?  You can register
custom marks to avoid this warning - for details, see …
```
> Avoid PytestUnknownMarkWarning by registering custom mark

- annif/backend/fasttext.py
- annif/backend/pav.py
- annif/cli.py
- annif/corpus/types.py
- annif/project.py
- tests/projects.cfg
- tests/test_backend_fasttext.py
- tests/test_backend_pav.py
- tests/test_backend_vw_multi.py
- tests/test_cli.py
- tests/test_corpus.py
- tests/test_project.py
Closes #318.
Adding `exists=True` argument to `type=click.Path()` enables Click to check the existence of paths, for example:
```
$ annif train tfidf-en nonexistent.tsv
Usage: annif train [OPTIONS] PROJECT_ID [PATHS]...
Try "annif train --help" for help.
Error: Invalid value for "[PATHS]...": Path "nonexistent.tsv" does not exist.
```
There are now [tests](https://github.com/NatLibFi/Annif/commit/67840a944dcae55dc0ba23949c300e7b10dd0947) for raising these errors for every command, but to me they actually seem a bit too much. After all, there is no actual Annif code that these tests check. To not bloat the test code base, should the test be removed or reduced in number?
The case of missing training file now maps to `/dev/null`, but as noted, it doesn't work in Windows. This behaviour would …
> Issue318 handle missing or invalid path input for commands

- annif/backend/backend.py
- annif/backend/dummy.py
- annif/backend/fasttext.py
- annif/backend/mixins.py
- annif/backend/pav.py
- annif/backend/vw_ensemble.py
- annif/backend/vw_multi.py
- annif/project.py
- tests/projects.cfg
- tests/test_backend.py
- tests/test_backend_fasttext.py
- tests/test_backend_http.py
- tests/test_backend_pav.py
- tests/test_backend_tfidf.py
- tests/test_backend_vw_ensemble.py
- tests/test_backend_vw_multi.py
- tests/test_project.py
Implemented one initial approach for discussion.
In this good is that default parameters can be included only in the relevant base classes for a backend (e.g. `chunksize` in `ChunkingBackend`). The Fasttext and VW params could be included to `DEFAULT_PARAMS` too (with a bit of work for passing only the backend specific params to the backends). 
Not-so-good is maybe the location of this, should it be in `project.py` instead? 
Another completely different approach could be to use to use [ConfigParser's defaults implementation](https://pymotw.com/3/configparser/#using-defaults).
> Issue273 default values for configuration settings

- annif/analyzer/analyzer.py
- annif/backend/backend.py
- annif/backend/tfidf.py
- annif/corpus/convert.py
- annif/project.py
- tests/test_project.py
This PR contains several different optimizations meant to speed up training of tfidf models, which are currently quite slow to train:
1. When converting the corpus to document-oriented (one line/file per document) to subject-oriented (one file per subject) format, delay the writes by buffering some data before writing it. This drastically reduces the number of required I/O operations.
2. Transform the corpus to subject-oriented before building the TfidfVectorizer, instead of doing it implicitly as part of the vectorization. I'm not sure why but this is much faster.
3. Add some caching to the Analyzer.is_valid_token method, which gets called a lot.
4. Move the subject vectorizer creation from the Project class to the TfidfBackend class. Originally I envisioned that there would be other …
> Optimizations to tfidf backend training

- annif/backend/pav.py
- annif/backend/vw_ensemble.py
- annif/backend/vw_multi.py
- annif/corpus/subject.py
- annif/eval.py
- annif/suggestion.py
This PR changes the data type of many NumPy arrays used to encode subject and suggestion vectors. Suggestions are now encoded using float32 (instead of float64) and known subjects are encoded using boolean arrays (instead of int8).
The end result is reduced memory usage and in some cases also faster execution. For example the `eval` command on a `tfidf` backend is now noticeably faster (around a third in one test).
Among other improvements this should reduce the memory consumption of the PAV backend during training (#339)
> Reduce vector memory usage

- Dockerfile
[Drone builds](https://drone.kansalliskirjasto.fi/NatLibFi/Annif/334/1/2) were failing. This was due to that the docker base image was pinned to tag `3-slim-buster`, whose [Python version was updated from 3.7 to 3.8](https://hub.docker.com/_/python?tab=description&page=1&name=3.7-slim-buster). 
Fix by pinning the tag to `3.7-slim-buster`.
> Pin Python docker image version to 3.7 to fix build error

- annif/eval.py
- tests/test_cli.py
Fixes #350
Show an error instead of crashing when trying to evaluate an empty corpus.
> Fail gracefully when trying to evaluate an empty corpus. 

- annif/backend/maui.py
This avoids encoding problems when Maui Server is run under Tomcat. Tomcat assumes that POST request content is ISO-8859-1 encoded (following the relevant specs) unless you tell it otherwise.
> Explicitly set charset=utf-8 for POST requests to Maui Server. 

- annif/cli.py
- annif/corpus/document.py
- annif/corpus/subject.py
- annif/project.py
- tests/corpora/archaeology/subjects-bom.tsv
- tests/projects_for_config_path_option.cfg
- tests/test_cli.py
- tests/test_corpus.py
Fixes #307 
This PR changes the way text files (including `projects.cfg`, TSV and TXT files) are read in order to handle UTF-8 byte order marks (BOM) gracefully. In practice, we just switch from `utf-8` encoding to `utf-8-sig`, which ignores existing BOMs.
> Fix UTF-8 BOM issues when reading files

- annif/eval.py
- tests/test_eval.py
I find that I often want to see the F1 score at K=5, i.e. when the suggestions are limited to the top 5 subjects. Currently this requires using `annif eval --limit 5 ...` but this is inconvenient and I often forget the `--limit` parameter. 
This PR adds F1@5 to the list of evaluation results.
The `filter_pred_top_k` function is a bit awkward - my NumPy array mangling skills weren't enough to implement the logic without resorting to a `for` loop. It can be changed later if necessary, and the unit test verifies that it at least gives the correct result.
> Add F1@5 evaluation metric

- annif/backend/nn_ensemble.py
Fixes #355
This PR just adds the `learn-epochs` parameter. Making it possible to set/override that parameter on the command line is left for #250.
> Add learn-epochs parameter for nn_ensemble backend

- annif/backend/backend.py
- annif/backend/dummy.py
- annif/backend/ensemble.py
- annif/backend/fasttext.py
- annif/backend/http.py
- annif/backend/maui.py
- annif/backend/mixins.py
- annif/backend/nn_ensemble.py
- annif/backend/pav.py
- annif/backend/tfidf.py
- annif/backend/vw_base.py
- annif/backend/vw_ensemble.py
- annif/backend/vw_multi.py
- annif/project.py
- tests/conftest.py
- tests/test_backend.py
- tests/test_backend_fasttext.py
- tests/test_backend_http.py
- tests/test_backend_maui.py
- tests/test_backend_nn_ensemble.py
- tests/test_backend_pav.py
- tests/test_backend_tfidf.py
- tests/test_backend_vw_ensemble.py
- tests/test_backend_vw_multi.py
This PR changes the way backends access the project object. Before this PR, the project was passed as a parameter to the `train`, `learn` and `suggest` methods and the backend didn't store a permanent reference to the project. (In early versions, projects and backends were more independent than they currently are, and a single backend could be attached to multiple projects.)
With this change, the project is passed to the backend as a constructor parameter and stored in a field `self.project`. There is no need to pass it around internally within backends, which simplifies the code quite a lot.
> Refactor backend project

- .drone.yml
It is unnecessary to run Docker builds for every push to all branches (especially as a build dryrun is made for PR anyway), and apparently it has the negative consequence of stressing the Drone server and its network leading to timeout errors in the builds. 
Even for PRs the build dryruns are a bit questionable, running build&tests would be more meaningful, see #315.
> Disable build dryruns for pushes

- annif/project.py
When starting Annif as a WSGI server using gunicorn, I noticed errors like this:
```
Misconfigured project 'maui-fi': analyzer setting is missing (and needed by the backend)
Misconfigured project 'nn-ensemble-fi': analyzer setting is missing (and needed by the backend)
```
These are incorrect - maui and nn_ensemble don't need an analyzer since they're not directly processing text. This PR fixes the problem that caused these messages.
> Fix for spurious "analyzer setting is missing" errors under WSGI

- .travis.yml
- Dockerfile
- annif/backend/omikuji.py
- setup.py
This PR updates the Omikuji dependency to version 0.2.
* adds support for `collapse_every_n_layers` hyperparameter, needed for AttentionXML style layer collapsing
* enables Omikuji for Python 3.8
> Upgrade omikuji 0.2

- annif/backend/maui.py
- tests/test_backend_maui.py
Fixes #372
When support for overriding backend parameters during train and learn was implemented in #289, the Maui backend was forgotten and as a consequence it stopped working in Annif 0.45 (see #372 
This PR implements the necessary changes to make it work again and to support overriding parameters during training.
> Adapt the Maui backend for backend parameter overriding. 

- annif/swagger/annif.yaml
`annif.dev.finto.fi` was updated to use `https` instead of `http`, and this change allows Swagger use it.
> Enable https in Swagger

- annif/backend/fasttext.py
- annif/backend/maui.py
- annif/backend/nn_ensemble.py
- annif/backend/omikuji.py
- annif/backend/pav.py
- annif/backend/tfidf.py
- annif/backend/vw_multi.py
- annif/cli.py
- annif/project.py
- tests/test_backend_fasttext.py
- tests/test_backend_maui.py
- tests/test_backend_nn_ensemble.py
- tests/test_backend_omikuji.py
- tests/test_backend_pav.py
- tests/test_backend_vw_multi.py
- tests/test_cli.py
Real support is implemented for now only in fasttext, omikuji and vw_multi backends.
Fixes #342
> Implement --cached option for train command

- annif/backend/pav.py
This PR changes the way the PAV backend stores the true labels and scores returned by source projects during training. They are now kept as (SciPy) sparse vectors, which saves a significant amount of RAM. Training times and suggestion results are the same as before.
Part of #377
> Use sparse vectors in PAV backend

- .travis.yml
- Dockerfile
- annif/backend/nn_ensemble.py
- setup.py
- tests/test_backend_nn_ensemble.py
Before this PR, the nn_ensemble backend collected score and label (target) vectors in memory, which took a lot of RAM when there are thousands of documents, multiple source projects and a large vocabulary such as YSO. This PR makes the nn_ensemble backend instead spool those vectors into an on-disk, memory-mapped LMDB database instead (implemented as a keras.utils.Sequential subclass). The vectors are also compressed by representing them as SciPy sparse vectors.
The LMDB training data can also be reused in later training rounds by using the recently introduced `--cached` option, although this functionality is not yet implemented in the initial commit.
Fixes #363
> Use LMDB and sparse vectors in nn_ensemble backend

- annif/backend/maui.py
- annif/cli.py
The option to override BE params was added as a decorator to most CLI commands in #289, but the option was already existing in the optimize command, and I did not notice to remove it at that time. This led only to duplication of the option in the CLI help message.
Also updates the log message about initializing Maui Service tagger to Maui Server, left from #344 .
> Remove duplicated be param option

- setup.py
The following issue was [reported in Annif users mailing list](https://groups.google.com/d/msgid/annif-users/CADt3EczfLFxCn3jdkN9D3DP1O6erC0U0aLyiEjPHyUJDCXKktg%40mail.gmail.com?utm_medium=email&utm_source=footer):
```
$ cat doc.txt | annif suggest fasttext-en
[...]
TypeError: multilinePredict(): incompatible function arguments. The following argument types are supported:
1. (self: fasttext_pybind.fasttext, arg0: List[str], arg1: int, arg2: float, arg3: str) -> List[List[Tuple[float, str]]]
Invoked with: <fasttext_pybind.fasttext object at 0x7fb7f47c7ca8>, ['a lot of words\n'], 100, 0.0
```
This is due to multiple versions of fasttext packages being installed, which is fixed by removing the wrong one.
> Remove "fasttext" package

- annif/corpus/subject.py
- annif/suggestion.py
- annif/vocab.py
- tests/test_suggestion.py
- tests/test_vocab.py
> Issue274 retain subject ids when loading vocabulary over existing one

- projects.cfg.dist
Example Maui projects in `projects.cfg.dist` have been showing the use of deprecated Maui Service via http backend, which is now updated to Maui Server backend. 
Also adds example projects for omikuji backend.
> Update projects.cfg.dist to show the use of Maui Server and omikuji

- Pipfile
- setup.py
- tests/test_cli.py
Click 7.1.1 was [released yesterday](https://palletsprojects.com/blog/click-7-1-released/). Annif didn't depend on a specific version of Click, so the Travis CI tests immediately started using it. Some of the annif.cli tests failed because the new Click version uses a slightly different quote style in error messages.
This PR pins Click to version 7.1.* and fixes the tests to match the new Click error messages.
> Fix click 7.1 compatibility in tests

- .readthedocs.yml
- docs/conf.py
- docs/requirements.txt
This PR fixes three issues related to readthedocs builds.
1. Since the release of [Werkzeug 1.0.0](https://pypi.org/project/Werkzeug/#history) on Feb 6 2020 builds of Annif documentation in RTD have been silently totally failing (not outputting docstring contents at all). [RTD logs](https://readthedocs.org/api/v2/build/10687085.txt) showed only warnings like:
```
WARNING: autodoc: failed to import module 'cli' from module 'annif'; the following exception was raised:
cannot import name 'FileStorage' from 'werkzeug' (/home/docs/checkouts/readthedocs.org/user_builds/annif/envs/move-sphinx-packages-to-docs-requirements.txt/lib/python3.7/site-packages/werkzeug/__init__.py)
```
As discussed [here](https://github.com/zalando/connexion/issues/1149), for now this is fixed by pinning Werkzeug to …
> Fix silently failing rtd builds

- Pipfile
- README.md
- docs/conf.py
- docs/requirements.txt
Three small enhancements for docs:
1. Move all `sphinx` packages from `Pipfile` to `docs/requirements.txt` as they are needed only in RTD builds.
2. Add RTD build status badge to `README.md`.
3. Show relese tag tailed with commit hash in the "latest" doc version, like `0.46.0-19-g8dd52d0` instead of just `0.46.0` (which is shown in "stable" doc version).
> Misc rtd enhancements

- annif/templates/home.html
Fixes #390. 
Now notations are just added after label, for example: 
Should notations be somehow more distinctly separated from the labels, e.g. `[42.42]`? 
Or maybe it would be better to show them before the label? Like this:
> Show notations in web UI results list

- annif/backend/maui.py
- annif/suggestion.py
- tests/test_backend_maui.py
This PR changes the way failed operations are handled in the Maui backend
* The error messages from Maui Server are now reported to the user. Fixes #401
* Don't break if Maui Server returns bad or unknown URIs (e.g. due to [this bug](https://github.com/NatLibFi/maui/issues/5)). Fixes #389
* Exception nesting is now done properly
> Improved error handling in maui backend

- Dockerfile
- setup.py
Tensorflow 2.1 introduced [GPU support that comes by default](https://github.com/tensorflow/tensorflow/releases/tag/v2.1.0). 
Currently Annif does not benefit from the GPU support (some needed libraries are not even installed in the Docker image), but the Tensorflow with GPU support takes quite much disk space (it bloats Annif's Docker image from 1.4 GB to 2.4 GB).
It is better to install Tensorflow with only CPU support.
> Install CPU-only version of Tensorflow

- .travis.yml
I noticed that the Travis CI builds for Python 3.6 take a significantly longer time than those of 3.7, with 3.8 in the middle. This PR changes the Travis configuration so that fastText related tests are run in the Python 3.7 environment, not Python 3.6, which evens out build times somewhat.
> Run Travis CI fastText tests on Python 3.7 instead of 3.6

- Dockerfile
- setup.py
There is nothing important in omikuji 0.3.x that would affect Annif use AFAICT, but upgrading to the newest version (currently 0.3.1) just to stay up to date.
> Upgrade to omikuji 0.3.x

- Dockerfile
- setup.py
Fixes two issues related to the new fasttext version:
* I forgot earlier to update the fasttext version in the Dockerfile in PR #409 
* Pins the fasttext version to 0.9.2 since we don't know whether newer releases are compatible
> Pin fasttext version to 0.9.2 and fix fasttext version in Dockerfile

- annif/backend/ensemble.py
- annif/backend/nn_ensemble.py
- annif/backend/pav.py
- annif/backend/vw_multi.py
- annif/project.py
- annif/util.py
- tests/conftest.py
- tests/test_backend_nn_ensemble.py
- tests/test_backend_pav.py
- tests/test_backend_vw_multi.py
- tests/test_project.py
The beginnings of implementing #65. At the moment this draft PR only contains commits that separate the Annif project handling from the Flask current_app object. Making a PR to get early feedback from QA tools.
> Separate Annif projects from Flask current_app

- annif/backend/backend.py
- annif/backend/dummy.py
- annif/backend/ensemble.py
- annif/backend/http.py
- annif/backend/maui.py
- annif/backend/nn_ensemble.py
- annif/backend/pav.py
- annif/cli.py
- annif/project.py
- annif/swagger/annif.yaml
- tests/conftest.py
- tests/test_backend_http.py
- tests/test_backend_maui.py
- tests/test_backend_nn_ensemble.py
- tests/test_backend_pav.py
- tests/test_cli.py
- tests/test_project.py
Implements some features of #329.
Adds 
- `Trained` column to `list-projects` CLI command
- `Trained` and `Modification time` rows to `show-project` CLI command 
- `is_trained` and `modification_time` fields to the REST API responses showing project info
> Show project train state and modification time

- annif/templates/home.html
Remove an empty entry in the Vue.js UI. With the change, the first element of project list is selected by default. Therefore the user does not need to select a project manually.
> WEB-UI: Remove empty entry from list of projects.

- setup.py
SciPy 1.5.0 was just released, but TensorFlow 2.2.0 complains that it needs 1.4.1.
> Pin SciPy to 1.4.1 as required by TensorFlow 2.2.0

- annif/templates/home.html
My last PR selected the first project only visually. When trying to analyze text in the web UI, before selecting another project than the first, the user was asked to select a project. The only way to select the first project was to select another project and then again select the first project from the drop down menu. Sorry for the mess.
> Assign first retrieved project to selected variable.

- annif/cli.py
> Rename variable that would otherwise shadow the builtin function map

- annif/corpus/subject.py
- annif/eval.py
- annif/suggestion.py
- tests/test_corpus.py
- tests/test_suggestion.py
This PR changes the way NumPy arrays are allocated during evaluation operations. Instead of allocating N one-dimensional vectors (where N is the number of documents) and then combining them into a single 2D vector, the 2D vector is allocated up front. This reduces the memory usage a bit. I was hoping to see a speedup as well, but so far it seems there is no measurable difference. I will run a few more benchmarks to verify before merging.
TODO:
- [ ] check and address QA tool complaints
> Memory optimization: Avoid double allocation of NumPy arrays in eval operation

- annif/cli.py
Adds short form CLI options, e.g. `-l` as an alias for `--limit`, `-t` for `threshold` and `-j` for `--jobs`
Some docstrings also improved
> Define short form for CLI options and fix some of their docstrings

- annif/backend/backend.py
- annif/backend/http.py
- annif/backend/maui.py
- tests/test_backend_http.py
- tests/test_backend_maui.py
- tests/test_backend_nn_ensemble.py
- tests/test_backend_pav.py
- tests/test_project.py
The handling of timezones in modification timestamps was inconsistent. One symptom of this was the problem handling Maui Server timestamps (#431) but there were other issues as well, such as not being able to parse all RFC3339 compliant formats, problems with fractions of seconds etc.
This PR fixes many related issues. The basic principles are:
* modification times are now represented internally as timezone-aware datetime objects, always with timezone set to UTC
* use `dateutil.parser.parse` to parse incoming date strings (from Maui Server or HTTP endpoint), since it can handle many format variations
Fixes #431
> Make modification timestamps timezone-aware

- Dockerfile
- setup.py
TensorFlow 2.3.0 was just released. This PR updates Annif to use it. None of the changes in the 2.3.0 release seem relevant for Annif, so this is just for keeping up to date.
> Upgrade TensorFlow to version 2.3.0 (from 2.2.0)

- Dockerfile
- setup.py
While working on #444 I noticed that there was a new release of LMDB, with a new (semantic) version number scheme.
This PR upgrades the LMDB dependency from 0.98 to 1.0.0. The actual changes should be very minor.
> upgrade LMDB dependency from 0.98 to 1.0.0

- annif/backend/nn_ensemble.py
- annif/backend/pav.py
- tests/test_backend_nn_ensemble.py
- tests/test_backend_pav.py
As noted in #446 there was a bug concerning the default parameters in PAV and nn_ensemble. 
> > and with nn_ensemble there is similar case.
> 
> I don't see the problem there? The default parameters are combined from the superclass and the current class.
For some reason the default parameters from AnnifBackend were not present in NNEnsembleBackend (for now only the `limit` parameter). Seems like even if the "right method" i.e. `default_params(self)` from AnnifBackend was in use via `super()`, the `self` in this case was the object of NNEnsembleBackend class, which has its own `DEFAULT_PARAMETERS` field.
> Fix missing default params in pav and nn ensemble

- annif/project.py
This fixes one `DeprecationWarning` that `pytest` has been giving for a while:
```
tests/test_project.py::test_project_train_state_not_available
/home/local/jmminkin/git/Annif/annif/project.py:175: DeprecationWarning: The 'warn' method is deprecated, use 'warning' instead
logger.warn('Could not get train state information.')
```
(Two other `DeprecationWarning`s remain, but they are from TensorFlow package.)
> Resolve DeprecationWarning by pytest: change warn to warning

- annif/backend/backend.py
- annif/corpus/__init__.py
- annif/corpus/document.py
- tests/test_backend_tfidf.py
- tests/test_corpus.py
…learn
Would this approach be suitable? Another way would be to apply the limit when each backend uses the document texts.
Now I see the limit would need to be applied also in [`DocumentList` class](https://github.com/NatLibFi/Annif/blob/input-limit-for-corpus-document-texts/annif/corpus/document.py#L91) as it is used by REST learn method.
> Apply the input_limit backend parameter to texts in train & learn 

- annif/corpus/__init__.py
This PR addresses a number of similar complaints by SonarCloud: the `__all__` list defined in `__init__.py` [should consists of strings](https://docs.python.org/3/tutorial/modules.html#importing-from-a-package).
> Address SonarCloud complaint: use strings in __all__ statement

- tests/test_cli.py
This PR fixes a bug reported by SonarCloud. A test had an expression that didn't have any effect. Replaced it with proper assertions.
> Address SonarCloud complaint: add proper assertions for test result

- annif/backend/nn_ensemble.py
- annif/util.py
This PR contains fixes aiming at improving the way the NN ensemble handles sources that have been assigned non-default weights.
1. The weights assigned to source backends are now always normalized so that they add up to 1 (L1 normalization).
2. The NN ensemble multiplies incoming score vectors by the assigned weights. Since the normalized weights are now generally smaller than they used to be (e.g. not 1:1:1 but 0.33:0.33:0.33), they are multiplied - outside the neural network - by the number of sources to compensate for this change.
3. While researching this, I discovered that the NN ensemble performs better when the incoming weights are slightly larger numerically. Taking the square root of the scores (which increases the scores, since sqrt(x) > x when 0<x<1) before feeding them to the …
> Improved handling of source weights in NN ensemble

- annif/backend/maui.py
- tests/test_backend_maui.py
Fixes #459
The `limit` parameter is used to set the `max_topics_per_document` setting for the Maui tagger created during train time. This makes it possible to get more than 10 (the default) results from Maui Server.
> Pass limit parameter to Maui Server during train

- annif/corpus/document.py
- tests/test_corpus.py
When trying to train some Omikuji based model with `input-limit` parameter I ran into an error:
```
$ annif train yso-bonsai-fi tests/corpora/archaeology/documents.tsv -b omikuji.input_limit=42
Backend omikuji: creating vectorizer
warning: Unknown subject URI <http://example.org/dummy_subject>
warning: Unknown subject URI <http://example.org/dummy_subject>
Backend omikuji: creating train file
2021-01-22 17:11:09,628 INFO  [omikuji::data] Loading data from data/projects/yso-bonsai-fi/omikuji-train.txt
2021-01-22 17:11:09,628 INFO  [omikuji::data] Parsing data
2021-01-22 17:11:09,629 INFO  [omikuji::data] Loaded 0 examples; it took 0.00s
2021-01-22 17:11:09,629 INFO  [omikuji::model::train] Training model with hyper-parameters HyperParam { n_trees: 3, min_branch_size: 100, max_depth: 3, …
```
> Fix TruncatingCorpus iterator 

- annif/cli.py
- annif/corpus/__init__.py
- annif/corpus/document.py
- tests/test_cli.py
- tests/test_corpus.py
This adds a CLI option `--docs-limit/-dl` to the commands where it is applicable. The option can be used to limit the number of documents to process to create learning-curve data, for example. [Learning curves](https://scikit-learn.org/stable/modules/learning_curve.html#learning-curve) can help to estimate "what is enough training data". 
This CLI option can be used in a shell script with training and evaluation steps, and the complex implementation of #364 can be abandoned.
> Limit document number CLI option

- annif/suggestion.py
- tests/test_suggestion.py
Fixes #470
This is a really simple fix to ensure that the NN ensemble can never return a score below 0.0 or above 1.0.
I don't see any obvious downsides except it loses the distinction between, say, 1.0 (very sure this is correct) and 1.1 (extra sure this is correct!). An alternative would be to use some sort of activation function such as [sigmoid](https://en.wikipedia.org/wiki/Sigmoid_function) that squeezes any kind of score values into the range 0.0-1.0 but I think this would be overkill and the resulting typical score range would then probably not make a lot of sense.
Any opinions about this @juhoinkinen ? Would it be fine to merge this as is or should we do something else here?
I couldn't figure out a way to test this since it's pretty rare and it requires a heavily biased model to …
> Make sure suggestion scores are in the range 0.0-1.0

- tests/test_suggestion.py
While working on PR #470, I noticed that some tests in `test_suggestion.py` were inconsistently named and some of them took a `document_corpus` fixture which wasn't actually used. This PR cleans up those.
> Cleanup suggestion tests

- annif/backend/nn_ensemble.py
- tests/test_backend_nn_ensemble.py
When training nn-ensemble with optimizers that do not automatically adjust the learning rate it is helpful to configure it manually. Even with automatically adjusting optimizers, it may sometimes be beneficial to change the learning rate.
This pr allow to set the learning rate in the nn-ensemble project definition.
As different optimizers have different default learning rates, it is not possible to just add a default parameter. Instead the presence of a `lr` key in the config map is checked.
> Allow configuration of nn ensemble learning rate

- annif/cli.py
I noticed that the `annif optimize` command is extremely slow for ensemble projects. The problem was that the ensemble backends return VectorSuggestionResult objects, while regular backends (tfidf, omikuji, stwfsa...) usually return ListSuggestionResult objects. The `optimize` command does a lot of filtering of results (using different `limit` and `threshold` values) and this is a very slow operation with VectorSuggestionResult.
The fix is to ensure that the results given by the project are first converted to ListSuggestionResult. Conveniently, `VectorSuggestionResult.filter` already returns a ListSuggestionResult and in any case, it makes sense to pre-filter the results down to at most 15 suggestions since only the top 15 will be used anyway and keeping the others will just create more …
> Optimize the optimize command

- annif/suggestion.py
This PR implements a small optimization for situations where the subject vocabulary contains deprecated IDs.
Due to a small configuration mistake during testing, I messed up my subject vocabulary so that I had almost 4000 deprecated subject IDs. This caused most normal operations (suggest, eval, etc.) to slow down to a crawl. The problem was that subject IDs were being checked for memberhip in `deprecated_ids`, which is a list; this is an O(n) operation, where n is the number of deprecated IDs. Changing it to a `set` object makes this O(1) instead, avoiding the slowdown. It's probably rare to have a large number of deprecated IDs, but the fix is easy and doesn't hurt.
> Optimize check for deprecated subject IDs using a set

- annif/backend/stwfsa.py
- setup.py
- tests/test_backend_stwfsa.py
A PR for an updated version of stwfsa. The Improvements are:
* No more duplicate concepts in suggestions Fixes #478 
* Better support for long texts by using frequency and positional distribution features of concepts.
* Text Vectorizer is disabled by default to reduce memory requirements for large corpora.
* Improved Escaping of symbols in automaton construction
> Update stwfsa to 0.2.*

- annif/analyzer/analyzer.py
After PR #468 that introduced the `token_min_length` setting, old Omikuji models no longer work. They fail with this error:
```
File "/home/ozone/git/Annif/annif/analyzer/analyzer.py", line 28, in is_valid_token
if len(word) < self.token_min_length:
AttributeError: 'SnowballAnalyzer' object has no attribute 'token_min_length'
```
The problem is that the new code expects that the `token_min_length` field is always present. It was set by the new constructor, but old Analyzer objects (serialized alongside the model) don't have it.
This PR changes the implementation so that the field with a default value is defined for the class, but can be overridden in instances. This way old models will keep working, they will just rely on the default value.
Ping @mo-fu
> Backwards compatibility fix for the token_min_length setting

- annif/backend/mllm.py
This PR removes the `use_hidden_labels` parameter from the hyperparameter search in the MLLM backend. The reason is that `use_hidden_labels` affects the construction of the term index and this is done before hyperparameter optimization, so varying it won't affect the results of the hyperparameter search.
> MLLM fix: don't include use_hidden_labels in hyperopt, it won't have any effect

- setup.py
This PR upgrades the scikit-learn dependency from 0.23.2 to 0.24.*
This seems to work without any problems. stwfsapy has declared its dependency as `scikit-learn>=0.22.*` which is compatible as well.
This upgrade is required to get access to some new features in CalibratedClassifierCV, which is used in the SVC backend (PR #486)
> Upgrade scikit-learn to 0.24.2

- .codecov.yml
- .github/workflows/python-package.yml
When Annif's CI service was switched from Travis to GitHub Actions (#474) the uploading of unit-test coverage reports was not included in the GH Actions workflow, so the coverage report at [codecov.io](https://app.codecov.io/gh/NatLibFi/Annif/) has not been up to date.
This PR adds the [Codecov Action](https://github.com/codecov/codecov-action) to upload the coverage report. For public repositories this Action does not require the codecov token, which is removed from the `.codecov.yml`.
> Add Codecov Action to GH workflow for uploading reports

- .github/workflows/python-package.yml
- README.md
- annif/backend/__init__.py
- annif/backend/maui.py
- annif/backend/yake.py
- annif/corpus/skos.py
- annif/project.py
- annif/util.py
- annif/vocab.py
- projects.cfg.dist
- setup.py
- tests/conftest.py
- tests/test_backend_stwfsa.py
- tests/test_backend_yake.py
- tests/test_vocab.py
This PR adds a new backend to Annif by integrating the [YAKE](https://github.com/LIAAD/yake) library. 
YAKE performs unsupervised automatic keyword extraction, and in the Annif backend the keywords found by YAKE are searched from the SKOS vocabulary labels, and the matches are returned as subject suggestions. The search can be targeted to prefLabels, altLabels and/or hiddenLabels as set in project configuration. 
The YAKE backend is based on lexical principle, but does not perform as well as the other lexical backends (MLLM, STWFSA or Maui) as measured by evaluation results. However, the (free) keyword extraction operation offers a possibility to add new features in Annif, especially the feature for suggesting new terms for a vocabulary (the keywords not found in the vocabulary), see …
> YAKE backend

- annif/backend/yake.py
- tests/test_backend_yake.py
I noticed that a user could try to train a Yake project (which is unnecessary Yake being unsupervised algorithm), but training would seem to succeed, although actually nothing happens.
A more correct behavior is to raise `NotSupportedException` when training a Yake project is attempted, as in the case of the Ensemble backend.
> Raise NotSupportedException for attempt to train YAKE

- annif/cli.py
- tests/test_cli.py
Currently the version of Annif needs to be obtained by `pip list` or similar not very convenient way, and `annif --version` confusingly outputs the versions of Python, Flask and Werkzeug.
This PR makes the `--version` option to show only the version of Annif itself, utilizing the [Click decorator](https://click.palletsprojects.com/en/7.x/api/?highlight=version_option#click.version_option):
```
$ annif --version
0.53.0.dev0
```
> Add --version option to CLI

- annif/backend/__init__.py
- annif/backend/svc.py
- tests/test_backend_svc.py
This (draft) PR adds a new backend `svc` that implements Linear Support Vector Classification. It is based on LinearSVC in scikit-learn, which in turn is based on liblinear. This kind of algorithm is well suited for multiclass (but not multilabel) classification, for example classifying documents with the Dewey Decimal Classification. It requires relatively little training data.
TODO (at least):
> New SVC (support vector classification) backend using scikit-learn

- annif/backend/svc.py
- tests/conftest.py
- tests/test_backend_svc.py
Claudia [reported in annif-users email list](https://groups.google.com/g/annif-users/c/F8N9x2dBHYM/m/IbMXKwPeDQAJ) that they encountered problems when trying to train the SVC backend on full-text corpus. Their initial problem was not the one that this PR fixes, but their report brought this up.
Training SVC backend on fulltext corpus does not work but fails with `TypeError: 'set' object is not subscriptable`. This is because `DocumentDirectory` [defines uris for documents as a set](https://github.com/NatLibFi/Annif/blob/2b8e3c95e41305532516a9f51be5274788f5579a/annif/corpus/document.py#L46), while in SVC it was assumed that uris are list or other subscriptable (which for `DocumentFile` [is true](https://github.com/NatLibFi/Annif/blob/2b8e3c95e41305532516a9f51be5274788f5579a/annif/corpus/doc …
> Fix training SVC on fulltext corpus

- docs/requirements.txt
In the past in the documentation builds in [ReadTheDocs](https://annif.readthedocs.io/en/latest/) some dependencies have been needed, but lately (since v0.52) in installing them there has been a version conflict and the builds have been failing. This PR removes installing now unnecessary packages in docs building, and up-to-date documentation will be available again.
> Fix RTD build error due to package conflict

- annif/backend/nn_ensemble.py
- tests/test_backend_nn_ensemble.py
Training or learning NN ensemble projects on a corpus consisting of only one document has been failing due to `UnboundLocalError` from Keras. 
On Annif side the reason for this was an error for calculating [the number of batches in `LMDBSequence`](https://github.com/NatLibFi/Annif/blob/a1348aa42236446dc315ef9c3ed2ea4de00a2ceb/annif/backend/nn_ensemble.py#L72-74), which was based on a wrong `self._counter` value: when loading the LMDB the counter value [was obtained as the index of the last element](https://github.com/NatLibFi/Annif/blob/a1348aa42236446dc315ef9c3ed2ea4de00a2ceb/annif/backend/nn_ensemble.py#L41), which resulted in the counter value to be too small by one (for a corpus of one document `self._counter = 0`, and thus `len(seq) = 0`). So, Keras did not find any batches to …
> Fix NN ensemble training and learning on one-document corpus

- annif/backend/svc.py
- tests/conftest.py
- tests/test_backend_svc.py
PR #501 fixed training SVC on full-text corpus, and also added raising `NotSupportedException` if any training document had multiple uris (as SVC is a multi-class, not multi-label algorithm). However in real-life even in those data-sets meant to have only one subject per doc there can be some docs with many subjects. To allow training SVC on such data sets, this PR changes the error to warning, and lets a random one of the uris to be used as the target uri.
> Warn instead of error in case of multiple subjects per doc in SVC training

- annif/backend/nn_ensemble.py
This PR replaces the Lambda layer with a custom MeanLayer in the nn_ensemble backend. It was intended as a fix to the CustomMaskWarning error encountered in PR #499 (upgrade to TensorFlow 2.5.0) but it turned out that the problem is unrelated.
This might still be a good idea, for example it could improve the compatibility of saved nn_ensemble models between Python versions. But it needs more testing so I'm leaving this as a draft PR.
> Implement custom MeanLayer in nn_ensemble

- annif/corpus/document.py
- tests/test_backend_svc.py
Makes the type of the uris container in DocumentFile and DocumentDirectory the same, i.e. set.
Closes #502.
> Use set as container of uris instead of list in DocumentFile

- annif/backend/backend.py
- annif/backend/ensemble.py
- annif/backend/fasttext.py
- annif/backend/maui.py
- annif/backend/mllm.py
- annif/backend/nn_ensemble.py
- annif/backend/omikuji.py
- annif/backend/pav.py
- annif/backend/stwfsa.py
- annif/backend/svc.py
- annif/backend/tfidf.py
- annif/backend/vw_multi.py
- annif/backend/yake.py
- annif/cli.py
- annif/project.py
- tests/test_backend_fasttext.py
This PR adds a new `jobs` parameter for the `annif train` command, similar to the one already implemented in `eval` and `hyperopt` commands. The intent is to make it easier to control the amount of threads/CPUs used for training, for those backends that can make use of parallel processing during training.
The PR adds this support to the fasttext and Omikuji backends, for which this was simple to implement.
Adding as draft PR for now, since this needs more testing and QA tool checks.
This is a sideshoot of PR #511 which will benefit from this, but I thought it was cleaner to implement it as a separate PR.
> Support jobs parameter in train command

- annif/corpus/skos.py
- annif/vocab.py
- tests/test_cli.py
- tests/test_vocab.py
SKOS vocabulary parsing can be pretty slow. With the MLLM backend, the SKOS vocabulary needs to be parsed from a Turtle file every time models are trained. With current YSO this takes around a minute.
If we instead serialize the rdflib.Graph using joblib during loadvoc, it will be much faster to load during train runs.
I tested two versions (on i7-8550U laptop), one with uncompressed dumps and another with gzip compression, using the Annif-tutorial yso-nlf data set and the train command from the MLLM exercise. Note that the benchmark wasn't very scientific.
**-**|**loadvoc (s)**|**train mllm (s)**|**dump size**
-----|:-----:|:-----:|:-----:
Before|72|893|-
Uncompressed|106 (+34)|844 (-49)|51MB
Compressed|102 (+30)|856 (-37)|22MB
The gzip version seems better. Basically, this will add ~30s …
> Keep serialized dump of SKOS graph to save parsing time

- annif/backend/backend.py
- annif/backend/dummy.py
- annif/backend/ensemble.py
- annif/backend/fasttext.py
- annif/backend/mllm.py
- annif/backend/nn_ensemble.py
- annif/backend/omikuji.py
- annif/backend/pav.py
- annif/backend/stwfsa.py
- annif/backend/svc.py
- annif/backend/tfidf.py
- annif/backend/vw_multi.py
- annif/backend/yake.py
- annif/cli.py
- annif/project.py
- tests/test_backend_nn_ensemble.py
Fixes #453 by introducing a `parallel` parameter to project.initialize() and backend.initialize() methods. Setting it to True warns the project/backend that it will be used for parallel execution. The NN ensemble heeds this warning and delays loading the TensorFlow model until later, avoiding the lockup that otherwise happens.
Some unscientific benchmark results for the `eval` command examples in #453 using i5-7200U:
**-**|**user time (s)**|**wall time (m:s)**|
-----|:-----:|:-----:|
Before PR|279|4:42|
jobs=1|251|4:11|
jobs=2|329|2:47|
jobs=0|413|2:04|
Opening draft PR for QA tool results.
> Allow NN ensemble to be used for parallel eval

- annif/lexical/mllm.py
- annif/lexical/tokenset.py
- tests/test_lexical_tokenset.py
This PR improves the performance of the MLLM algorithm on large vocabularies with lots of repetition in the labels. The TokenSetIndex keeps the token sets indexed using a key token. Previously this key token was picked randomly, but this PR changes it so that the rarest token (among the terms of the subject vocabulary) is used as the key.
For example, if the vocabulary contains person entities like "John Smith", "John Taylor", "John Doe" and "John Johnson", they could all have been put in the index under the token `john`. Every time the document text contains the name "John", the index has to be searched and the tokens in the sentence compared with all the above token sets (`{john, smith}, {john, taylor}, {john, doe}, {john, johnson}`).
Instead the tokensets are now indexed under the …
> Use least frequent token as key in TokenSetIndex used by MLLM

- annif/corpus/skos.py
- annif/vocab.py
- tests/test_cli.py
- tests/test_vocab.py
This is a follow-up to PR #513 which introduced caching for parsed SKOS graphs as joblib dumps. Two small improvements:
- the filename is now `subjects.dump.gz` instead of `subjects.joblib.gz` which is hopefully a bit more descriptive
- `annif.util.atomic_save` is used to avoid file corruption problems in case the dumping gets interrupted
> SKOS graph cache enhancements

- annif/suggestion.py
This is a small optimization for the VectorSuggestionResult.filter() method. It creates a `limit_mask` object but to do so, it has to create a list containing all the subjects in the vocabulary. This list is immediately sliced to a much shorter length (typically 100 or 1000), so creating the full list is a waste of time.
This PR switches to using a generator expression instead of a list and slices it with `itertools.islice`, avoiding the list creation overhead. This saves approximately 0.2 seconds per document with the large GND vocabulary (and probably some memory too).
> Optimize limit_mask creation

- annif/cli.py
Fixes #521 
The intent was always that private projects can be accessed from CLI; the `access` setting only applies to the REST API. But this wasn't actually the case; hidden projects couldn't be used from most CLI commands due to a simple bug, fixed in this PR.
> Allow private projects to be accessed from CLI

- .drone.yml
Since Annif 0.53 Drone has not automatically built Docker images on git tag events as previously. The reason for the change is unclear to me, but removing the branch condition (restriction to `master`) from Drone build step triggers resolves the problem. 
Note that this also helps making patch releases: there is no more need to manually hardcode the tags in `.drone.yml` and the triggering branch as previously.
> Make Drone builds start on all git tag events

- annif/corpus/subject.py
Fixes #516 
When updating an existing vocabulary, every concept in the new vocabulary is checked to see if it exists in the old one. This check was implemented as a list membership check. But this O(n) check is hugely inefficient when the list is large, which is the case for a large vocabulary such as GND.
This one line PR changes the `contains_uri` to instead check for a key in a dict (which already existed within the SubjectIndex class), which is an O(1) operation and thus quick to do regardless of the size of the vocabulary.
Quick benchmark loading the GND vocabulary from a Turtle file:
- first load: 15 minutes
- update: 14 minutes
(the difference is probably not significant, it could have been due to swapping or other activity going on in the background)
> Much faster updating of existing large vocabulary

- setup.py
The http backend uses dateutil (since PR #432). This library was previously pulled in indirectly via alembic that optuna depends on. But the latest version of alembic makes this dependency optional, so it's no longer installed alongside optuna - and now installs are broken and CI tests are failing.
In any case, it's good practice to declare explicit dependencies to all the modules used in the codebase.
> Declare dateutil dependency

- Dockerfile
Updates the baseimage of Annif's Docker image to a newer Debian release.
The new Bullseye release has these Voikko packges:
```
libvoikko1/now 4.3-1+b1
voikko-fi/now 2.4-1
```
While the old Buster release has:
```
libvoikko1/now 4.2-1
voikko-fi/now 2.2-1.1
```
The update of the Voikko packages resolves the bad lemmatization results incorrectly producing "Määri" lemma, and this PR fixes #492.
> Update Docker baseimage to Debian Bullseye

- annif/backend/maui.py
- annif/backend/vw_multi.py
Maui and vw_multi backends will be removed in release 0.56. This PR makes Annif show a deprecation warning when training these backends.
> Add deprecation warning to Maui & vw_multi train commands

- Dockerfile
install the pycld3 package in Docker image, forgotten in #507.
> Install pycld3 in Docker image

- annif/analyzer/analyzer.py
- annif/analyzer/snowball.py
- annif/backend/__init__.py
- annif/cli.py
- tests/test_backend.py
Simplified version of PR #543
Fixes #514
The goal of this PR is to reduce CLI startup time by avoiding useless work, especially imports that are not necessary for the requested operation.
It makes the following changes to the import statements within the Annif codebase:
- complete rewrite of `annif/backend/__init__.py`; the end result is that backends (and the libraries they require, e.g. fasttext, omikuji and tensorflow) are only imported when they are actually used
- avoid importing NLTK and sklearn unless actually required, by moving import statements inside functions and methods
I tried to craft the changes to have minimal impact on the code so I only chose to make imports local in cases where there were very few uses within the same module.
Startup time for simple commands such as …
> Optimize startup time using local & lazy imports (take 2)

- Dockerfile
Currently we provide a Dockerfile and an image in quay.io with dependencies for all the optional features.
If someone does not need all the features, but e.g. uses only Omikuji backend and would like build their own image (e.g. for smaller size), they could edit the Dockerfile dropping the unwanted (Python) dependencies from the pip install command. However, using `--build-arg` option of `docker build` provides a way to pass the user-defined list of dependencies to install that overrides the default list:
```
docker build -t annif-omikuji-voikko --build-arg optional_dependencies=omikuji,voikko .
```
A user wanting to have a Docker image to use with Xtransfomer could add `pecos` to the default list in build time.
> Allow selecting installed optional dependencies in Docker build

- .github/workflows/python-package.yml
- README.md
- setup.py
The latest versions of many dependencies have dropped support for Python 3.6, so to be able to use them, also for Annif the support for Python 3.6 is dropped. See the discussion in #549.
With this PR that essentially means only removing running CI unit tests on Python 3.6 and updating the [requirement in `setup.py`](https://github.com/NatLibFi/Annif/blob/17108947010bb9cd7ea23811c92f0641c5588649/setup.py#L21).
> Drop Python 3.6 support

- setup.py
- tests/conftest.py
- tests/test_swagger.py
The [swagger-tester](https://github.com/Trax-air/swagger-tester) seems unmaintained and depends on [connexion](https://github.com/zalando/connexion). Since Annif is switching to install connexion (#549) from its new PyPI project (named [connexion2](https://pypi.org/project/connexion2/)), the result is that connexion ends up to be installed twice (currently as `connexion v2.7.0` and `connexion2 v2.10.0`).
This PR removes the swagger-tester dev dependency from Annif and adds self-written tests for REST API methods, so only `connexion2` will be installed. 
Also avoids running Flask in a background thread (at least explicitly) by [using Flask's TestClient](https://flask.palletsprojects.com/en/2.0.x/testing/#the-testing-skeleton).
Now the tests cover basically only the status codes related to …
> Remove swagger-tester dependency 

- annif/backend/omikuji.py
- annif/backend/pav.py
- annif/backend/tfidf.py
- annif/eval.py
- annif/lexical/mllm.py
- annif/lexical/util.py
- annif/suggestion.py
- setup.py
Dependency updates for Annif v0.56.
Updates to (edited):
- Omikuji 0.4.x
- TensorFlow 2.7.0 & lmbd 1.3.0
- Gensim 4.1.x
- joblib 1.1.0
- Optuna 2.10.x
- SciPy 1.7.x
- Scikit-learn 1.0.2
- NumPy 1.21.x
- Click 8.0.x
- Flask >=1.0.4,<3
- Connexion to use [connexion2 PyPI project](https://pypi.org/project/connexion2/)
Below is a table of Omikuji 0.3.4 and 0.4.1 models comparison. Training was performed on full Finnish Finna dataset (real and user times include preprocessing), and evaluation in parallel.
|                    |                     | v0.3   | v0.4   |
|--------------------|---------------------|--------|--------|
| train time         |                     |        |        |
|                    | real                | 190m   | 174m   |
|                    | user …
> Update dependencies v0.56

- .scrutinizer.yml
I noticed Scrutinizer was still running on Python 3.6 and installing code with pipenv, although those are not anymore in use with Annif (since #550 and #405). So in Scrutinizer runs this changes 
- Python version to 3.8.12
- Use directly pip instead of pipenv
(Draft PR first to see if this works.)
> Update Scrutinizer config

- annif/backend/nn_ensemble.py
- tests/test_backend_nn_ensemble.py
This PR adds the simple solution to close #552, as discussed in the issue.
> Make LMDB map size a configurable parameter for `nn_ensemble` backend.

- .github/workflows/python-package.yml
- Dockerfile
- annif/analyzer/__init__.py
- annif/analyzer/analyzer.py
- annif/analyzer/simple.py
- annif/analyzer/snowball.py
- annif/analyzer/spacy.py
- annif/analyzer/voikko.py
- annif/backend/yake.py
- setup.py
- tests/test_analyzer.py
- tests/test_analyzer_spacy.py
- tests/test_analyzer_voikko.py
Initial draft PR of new spaCy based (optional) analyzer.
Fixes #374
TODO items:
> Add spaCy analyzer

- annif/cli.py
- annif/eval.py
- annif/util.py
- tests/test_cli.py
- tests/test_util.py
This PR adds an option `-M`/`--metrics-file` to the `annif eval` command, like this:
annif eval my-project --metrics-file metrics.json /path/to/my-test-corpus/
The command writes evaluation metrics into the file in a format like this:
```json
{
"Precision (doc avg)": 0.12429731417863835,
"Recall (doc avg)": 0.10921187650575533,
"F1 score (doc avg)": 0.11149022571570978,
"Precision (subj avg)": 0.841174914733954,
"Recall (subj avg)": 0.14326083068180426,
"F1 score (subj avg)": 0.21448794969174276,
"Precision (weighted subj avg)": 0.736846816147547,
"Recall (weighted subj avg)": 0.09503311258278145,
"F1 score (weighted subj avg)": 0.1529771375758776,
"Precision (microavg)": 0.6067653276955602,
"Recall (microavg)": 0.09503311258278145,
"F1 score (microavg)": 0.16432865731462926,
"F1@5": …
```
> Output eval metrics as a JSON file compatible with DVC

- annif/cli.py
- annif/eval.py
- tests/test_cli.py
This PR implements a new option `-m`/`--metric` for the `annif eval` command. It can be used (and repeated) to select the metric(s) to calculate, instead of all of them. Example:
annif eval my-project -m F1@5 -m NDCG /path/to/my-corpus
Fixes #545
This is useful for DVC as well to avoid introducing a lot of unnecessary metrics into experiments.
> Add --metric/-m option to eval command to select metric(s)

- .github/workflows/python-package.yml
Recently, many GitHub Actions CI jobs have been stalling. I don't know the root cause, but they are timing out after 6 hours.
This is clearly too long, since normally the jobs should take less than 5 minutes.
This PR sets a 10 minute timeout for CI jobs to avoid them being stuck for hours and hopefully making it easier to investigate the stalled runs.
> Set a 10 minute timeout for GitHub Actions CI jobs

- annif/backend/mllm.py
The MLLM backend was missing an import of annif.eval. This didn't always cause issues because usually it was imported by other modules such as annif.cli. It may have caused tests to occasionally hang on GitHub Actions CI.
This PR simply adds the missing import.
> Add missing import of annif.eval in MLLM backend

- annif/analyzer/spacy.py
- tests/test_analyzer_spacy.py
This PR moves the import of spaCy inside the SpacyAnalyzer class so that it will be imported only when actually used. It reduces the startup overhead of Annif by around 2 seconds when the optional spacy feature has been installed.
> Lazy import of spaCy to avoid startup overhead

- setup.py
This PR is a stopgap fix to avoid CI jobs getting stuck. This seems to be caused by changes in Coverage 6.3 - see https://github.com/nedbat/coveragepy/issues/1310
A better fix may be needed later but let's see what happens on the Coverage side first. Until then, this change should work around the problem.
Fixes #564
> Avoid coverage 6.3 as it causes some tests to hang

- annif/cli.py
- annif/config.py
- annif/default_config.py
- annif/registry.py
- setup.py
- tests/projects.toml
- tests/test_config.py
- tests/test_project.py
Using Annif efficiently with DVC requires that DVC understands the Annif configuration file; the current INI-style format is not supported by DVC (see #547).
This PR adds support for TOML as a configuration file format alongside the current one (which still works). Unless the path to the configuration file has been set using the `ANNIF_PROJECTS` environment variable or the `-p` command line option, the configuration will be read from `projects.cfg` if it exists, otherwise from `projects.toml`.
The main difference in the configuration syntax is that TOML requires string values to be quoted, e.g.
language="fi"
instead of
language=fi
The [tomli](https://github.com/hukkin/tomli) parser is used for parsing project configuration files with a `.toml` extension. It's a very minimal read-only, …
> Support TOML as a configuration file format alongside CFG/INI.

- annif/cli.py
- annif/vocab.py
- tests/test_vocab.py
This PR adds a `--force` option to the `annif loadvoc` command which will force replacing the vocabulary completely even when a vocabulary (subject index) exists.
Fixes #526
> Add --force option to loadvoc CLI command

- annif/backend/nn_ensemble.py
During training, the NN ensemble has to process the training documents through the source projects, collecting suggestions. Previously this was done sequentially and could take a lot of time, often dominating the time it takes to train a NN ensemble.
With this PR, the suggest operations are done in parallel on multiple CPUs, controlled by the `--jobs` parameter of the `annif train` command. The default is to use all CPUs.
Fixes #429
Opening a draft PR to get feedback from QA tools. More detailed testing and benchmarking still needs to be done.
> Perform suggest operations in parallel using multiprocessing in nn_ensemble

- annif/lexical/mllm.py
- annif/parallel.py
- tests/conftest.py
- tests/test_backend_mllm.py
I noticed that the unit tests weren't making use of the small fulltext document corpus included in the test suite (tests/corpora/archaeology/fulltext/). In this PR, I've added a fixture to use it and switched the MLLM tests to use it instead of document_corpus. This speeds up the MLLM tests by a lot (24s -> 2s on my laptop).
> Use fulltext corpus in MLLM tests which is much faster

- .github/workflows/python-package.yml
The `wheel` package has not been available for dependency installations for unit tests in GH Actions runs. There has been messages like
[`Using legacy 'setup.py install' for pyrsistent, since package 'wheel' is not installed.`](https://github.com/NatLibFi/Annif/runs/5214072336?check_suite_focus=true#step:5:276)
Installing `wheel` gets rid of the messages, possibly also making dependency installations faster.
This PR also makes sure `setuptools` is updated, making dependency installation environment the same as in building Dockerfile.
This issue came into attention via a [comment](https://github.com/NatLibFi/Annif/pull/572#discussion_r807677553) in #572.
> Ensure setuptools and wheel are installed & up-to-date in CI unit tests

- .github/workflows/python-package.yml
The PR checks list is a bit cluttered by 6 unit test runs: tests for both `push` and `pull_request` events on 3 Python versions, while testing on both events is (mostly) useless as they are (nearly) identical cases. 
On the `pull_request` event the tests are run on ["as the PR was merged"](https://stackoverflow.com/questions/57683943/github-actions-how-to-build-a-pull-request-as-if-it-were-merged?rq=1), so it is more meaningful case to test, and is needed also as the `push` event is not available from forks.
Running tests on all `push` events, however, is not so useful. On pushes the workflow is usually needed to be run only when the target is master branch (typically when a PR is merged or a release is made).
This changes the `push` event trigger to exclude other branches than master. …
> Avoid running duplicated tests on PRs

- annif/__init__.py
- setup.py
- tests/test_cli.py
Trying to resolve Warnings emitted by unit tests. 
This PR resolves the `DeprecationWarnings`
- by Flask: `The 'script_info' argument is deprecated and will not be passed to the app factory function in Flask 2.1.`
- by pkg_resources: `Creating a LegacyVersion has been deprecated and will be removed in the next major release`
Note for the future: when the Annif support for Python 3.7 is eventually dropped, then the installation of the `importlib-metadata` package can be dropped too, as in Python 3.8+ the same functionality is provided by the [`importlib.metadata` of the standard library](https://docs.python.org/3.8/library/importlib.metadata.html?highlight=importlib%20metadata#module-importlib.metadata).
About the remaining Warnings:
- The three flake8 related warnings seem to have an …
> Resolve some Warnings from unit tests

- .github/workflows/python-package.yml
This enables the [cache for dependencies that are installed with pip](https://github.com/actions/setup-python#caching-packages-dependencies) in GH Actions jobs, while ensuring that all dependencies are upgraded (also the non-direct dependencies) by using the [eager upgrade-strategy](https://pip.pypa.io/en/stable/cli/pip_install/#cmdoption-upgrade-strategy).
[Test runs](https://github.com/NatLibFi/Annif/actions/runs/1880497089) show that caching shortens the job run times ~30 s on average.
I leave this PR as draft, because this branch is based on `resolve-deprecation-warnings` branch ([some unit tests](https://github.com/NatLibFi/Annif/runs/5271480358?check_suite_focus=true) started failing due to pkg_resources), so #575 should be merged first.
> Enable pip cache in GitHub Actions CI jobs

- Dockerfile
- Install rsync to allow transferring models to OpenShift environment
- Ensure pip & setuptools are updated when building
- Install voikko system packages only if Voikko is included in optional dependencies
- Remove retry loop for nltk data download (hopefully not needed anymore, as the network problems encountered in Drone should not exist in GH Actions)
> Update Dockerfile v0.57

- setup.py
This adds two links to the Project links section of the PyPI page and changes the Homepage link. The result should resemble e.g. the [requests PyPI page](https://pypi.org/project/requests/).
- Change Homepage link to annif.org
- Add Source link to GitHub repo
- Add Documentation link to GitHub Wiki
> Improved Project links in PyPI page

- .github/workflows/cicd.yml
- setup.py
Dependency updates for Annif v0.57.
Updates to:
- Omikuji 0.5.x to [enable symlinking Omikuji datafiles](https://github.com/tomtung/omikuji/issues/38)
- TensorFlow 2.7.1 to [fix many vulnerabilities](https://github.com/tensorflow/tensorflow/releases/tag/v2.7.1)
- Connexion to again use its [original/main PyPI project](https://pypi.org/project/connexion/) instead of the [Connexion2 project](https://pypi.org/project/connexion2/) (which now seems to be abandoned).
I don't think there are other dependencies that can be upgraded (to keep Python 3.6-3.9 support) or are worth upgrading now, or are there some?
Still needs to check that old Omikuji and NN ensemble models keep working, but I would suppose so.
> Update dependencies v0.57

- .github/workflows/cicd.yml
In PR #574 the general `push` event workflow trigger was replaced by a branch-specific push trigger (namely `push.branches.master`). However, this or any branch-specific push trigger does not fire on pushing tags (even to the selected branch); there has to be also the `tags` trigger, as explained in the [docs](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#onpushbranchestagsbranches-ignoretags-ignore).
I already tried to make the 0.57 release by pushing tags, which did not work out. So, I'll merge this fix, update the git tag, and push the tags again, and then the release workflow/job is supposed to be run...
> Add tags trigger to GH Actions CI workflow

- .github/workflows/cicd.yml
Apparently the tags trigger of #581 needs a list of allowed tags (not like PR trigger, why so...), so I try `*` wildcard. [It could work](https://github.community/t/how-to-run-github-actions-workflow-only-for-new-tags/16075/15).
> Add wildcard tags workflow trigger

- annif/cli.py
- annif/config.py
- annif/default_config.py
- annif/registry.py
- tests/projects.d/projects.cfg
- tests/projects.d/projects.toml
- tests/test_cli.py
- tests/test_config.py
- tests/test_project.py
Adds support for a project configuration directory. Closes #584.
Checks for duplicated project IDs across all configuration files in the configuration directory, and raises `ConfigurationException` if any are found.
For now I chose `projects.d` as the name for the default configuration directory, because it is nicely in line with the `projects.cfg` and `projects.toml` names for the default configuration files. Downside is that this name can be confusing: one could use "projects directory" to refer to the (projects) configuration directory (`projects.d`) or the projects data directory (`data/projects`). Or even to the parent directory containing `projects.cfg` and `data/` (in Docker instances I have been using `/annif-projects` directory for this).
I open PR as draft now; this probably …
> Support for multiple configuration files in a directory

- .readthedocs.yml
- docs/requirements.txt
The [builds for readthedocs documentation](https://readthedocs.org/projects/annif/builds/16552879/) were not succeeding due to `ImportError: cannot import name 'contextfunction' from 'jinja2'`. This is fixed by upgrading sphinx to version 4.5.*. 
This PR also pins the build platform (Ubuntu and Python versions).
> Fix readthedocs documentation builds

- .github/workflows/cicd.yml
Upgrades GH Actions to latest versions, and pins the codecov and pypi-publish Actions commit hashes.
Upgrading codecov Action (from v1 to v3) necessitates generating the coverage report in xml format ([apparently this applies to both v2 and v3](https://github.com/codecov/codecov-action/issues/577)).
~Also makes the coverage report upload conditional: it is uploaded only by Python 3.8 test run. Until now, the report was uploaded three times (by Python 3.7, 3.8 and 3.9 runs). That may be the reason for weird coverage changes I have noticed (the coverage is different for different Python versions, and it is somewhat random which run finishes last, and I think the report by the last run overrides earlier ones).~
~Now I chose to upload the report by Python 3.8 run. This evens out the the …
> Update GitHub Actions

- annif/analyzer/simplemma.py
- setup.py
- tests/test_analyzer_simplemma.py
This PR upgrades the Simplemma dependency (which is used in the simplemma analyzer, added in #591) from version 0.6 to [0.7](https://github.com/adbar/simplemma/releases/tag/v0.7.0).
Simplemma now does the loading of language data internally, so the calling code could be simplified even more from what it was. There is no need for the `__getstate__` trick so that was deleted too.
Related to [this comment](https://github.com/NatLibFi/Annif/pull/592#issuecomment-1164140577)
Note that I haven't tested this for real (yet), just verified that the tests pass, so keeping it as a draft PR for now.
> Upgrade Simplemma to version 0.7

- setup.py
This PR fixes a recently surfaced [incompatibility](https://github.com/tholo/pytest-flake8/issues/87) that causes CI tests to fail. pytest-flake8 (version 1.1.1) is not compatible with flake8 version 5, released a few days ago. The PR pins the version of flake8 to 4.x, which fixes the issue for now but is probably not a good long term solution.
I think we need to reconsider the use of pytest-flake8. Many folks [seem](https://github.com/pypa/pep517/pull/147) [to](https://github.com/pytest-dev/pytest/issues/9217#issuecomment-965144375) [be](https://github.com/miketheman/pytest-socket/issues/82) abandoning this flaky (heh) integration and instead switching to a setup where flake8 is run outside pytest. I will open a separate issue about this.
> Pin flake8 to version 4.x to avoid pytest-flake8 breakage

- .github/workflows/cicd.yml
- README.md
- setup.py
- tests/test_cli.py
This changes CI/CD tests to be run on Python 3.8-3.10 instead on 3.7-3.9 and updates mentions of Python version support to 3.8+. Wiki may still need updates for this.
Also 
- upgrades pinned dependencies to newest available (except for [simplemma](https://github.com/adbar/simplemma/releases/tag/v0.7.0) as there is some breaking change), which is now possible since dropping Python 3.7 support
- switches to [use importlib of the standard library](https://github.com/NatLibFi/Annif/pull/592/commits/61df4def91065295709d5b45f8fb2ad4a1c7bc28), previously the 3rd party package was needed for Python 3.7
- [verifies installed packages have compatible dependencies](https://github.com/NatLibFi/Annif/pull/592/commits/3714fcd3d8adeb9fadcd4c050af23332f89ae3a7) using `pip check`
Compatibility of models …
> Add Python 3.10 support & update dependencies

- annif/corpus/skos.py
- annif/lexical/mllm.py
- tests/test_vocab_skos.py
Fixes #556 by modifying the way concepts from SKOS vocabularies are loaded. There are two main changes:
1. If a concept doesn't have a prefLabel in the configured language, but has a prefLabel without a language tag, use that instead.
2. If a concept doesn't have any suitable prefLabels (in the configured language, or without a language tag), generate a pseudo label from the qualified name (e.g. `yso:p12345` or `lcsh:sh85061212`)
This should improve the support for multilingual vocabularies and handle cases when SKOS data is missing language tags, which can happen for example when converting MARC21 records to SKOS like @macsag did when reporting #556.
Note that unlike the solution drafted in [this comment](), there is no BCP 47 style matching of language tag variants (e.g. `en` in the …
> Include labels without language tag and concepts without labels in vocabulary

- annif/cli.py
- annif/corpus/skos.py
- annif/corpus/subject.py
- annif/project.py
- annif/vocab.py
- tests/conftest.py
- tests/projects.cfg
- tests/test_cli.py
- tests/test_project.py
- tests/test_vocab.py
- tests/test_vocab_skos.py
This PR implements #559 - making vocabularies multilingual, so that there is no need to use separate language-specific vocabulary id's such as `yso-fi`, `yso-sv` and `yso-en`. Instead the vocabulary id `yso` can be used for all projects and the `loadvoc` command needs to be executed just once as it will detect which languages are available in the vocabulary and load the labels in all available languages.
It's also possible to define/override the language of labels, for example to use `vocab=lcsh(en)` in a Finnish language project.
The changes need to be carefully tested as they are quite disruptive. Documentation (including the Annif tutorial) should be updated, mainly by stripping language suffixes from vocabulary id's in examples. However, old examples (vocabulary id's with a language …
> Make vocabularies multilingual

- projects.cfg.dist
This little PR does two things to the example configuration file `projects.cfg.dist`:
- strip the language prefixes (e.g. `yso-en` becomes `yso`) from vocabulary IDs, as it's now unnecessary to use language-specific vocabularies after the introduction of multilingual vocabularies (PR #559)
- set the vocabulary for some ensemble projects that were missing the vocab setting
> Remove language suffixes from vocabulary ids in example config

- annif/backend/dummy.py
- annif/backend/ensemble.py
- annif/backend/fasttext.py
- annif/backend/mllm.py
- annif/backend/nn_ensemble.py
- annif/backend/omikuji.py
- annif/backend/pav.py
- annif/backend/stwfsa.py
- annif/backend/svc.py
- annif/backend/tfidf.py
- annif/cli.py
- annif/corpus/combine.py
- annif/corpus/document.py
- annif/corpus/subject.py
- annif/corpus/types.py
- annif/eval.py
- annif/lexical/mllm.py
- annif/parallel.py
- annif/project.py
- annif/rest.py
- tests/conftest.py
- tests/test_backend.py
- tests/test_backend_fasttext.py
- tests/test_backend_nn_ensemble.py
- tests/test_backend_omikuji.py
- tests/test_backend_pav.py
- tests/test_corpus.py
- tests/test_eval.py
- tests/test_project.py
- tests/test_transform.py
This PR refactors the SubjectSet class, which are used to represent gold standard / manually indexed subjects for training and evaluation documents, so that the SubjectSet class only stores numeric subject IDs instead of subject URIs and labels. It also changes the Document class to contain a SubjectSet instead of separate fields for subject URIs and labels. The end result is that internally, numeric IDs are used much more than before and the conversion from concept URIs and/or labels to subject IDs is performed earlier than before. The changes should simplify things overall and also likely improve efficiency (both RAM and CPU), although I haven't measured the difference.
This PR is very similar to PR #604 which did the same kind of overhaul for the SubjectSuggestion class.
> Refactor SubjectSet and Document to store subject IDs instead of URIs and labels

- annif/backend/yake.py
- annif/cli.py
- annif/corpus/__init__.py
- annif/corpus/document.py
- annif/corpus/skos.py
- annif/corpus/subject.py
- annif/corpus/types.py
- annif/eval.py
- annif/lexical/mllm.py
- annif/rest.py
- annif/vocab.py
- tests/conftest.py
- tests/corpora/archaeology/subjects.csv
- tests/corpora/dummy-subjects.csv
- tests/test_backend.py
- tests/test_backend_http.py
- tests/test_cli.py
- tests/test_corpus.py
- tests/test_eval.py
- tests/test_project.py
- tests/test_suggestion.py
- tests/test_vocab.py
- tests/test_vocab_csv.py
- tests/test_vocab_skos.py
- tests/test_vocab_tsv.py
This PR completes (hopefully) the switch to multilingual vocabularies (#559) started in PR #600 and continued in PRs #604 and #606. It changes the SubjectIndex so that it keeps track of labels in all available languages, not just one at a time. The index is stored on disk in a CSV file which stores the labels in different columns named e.g. `label_en`, `label_fi`, `label_sv` etc. It replaces the current short-lived format where separate TSV files for each language were used (`subjects.en.tsv`, `subjects.fi.tsv` etc.). It turned out to be easier and cleaner to have just a single file containing labels in all languages. CSV is a good format for this as the columns can be named in a header row, so there is some flexibility in which columns are used.
It is also possible to use this CSV format …
> multilingual SubjectIndex backed by CSV file

- annif/project.py
- annif/registry.py
- annif/vocab.py
- tests/test_vocab.py
Fixes #603
This PR makes the handling of vocabularies more efficient by making it possible to use a single AnnifVocabulary instance shared by multiple projects. The vocabularies are now stored in AnnifRegistry, similar to how projects are stored.
I did a little benchmarking. I set up TFIDF, MLLM and Parabel projects with YSO as the vocabulary, as well as an ensemble using these three as sources. I trained them using the archaeology test corpora from the test suite. Then I measured the user time and maximum RSS of two commands targeting the ensemble project: a simple `annif suggest` and a parallelized `annif eval -j4` command against the fulltext documents in the test suite, before and after this PR:
|           | time before | time after | RSS before | RSS after | …
> Store vocabs in AnnifRegistry so they are shared between projects

- annif/cli.py
- annif/rest.py
- tests/corpora/dummy-subjects.csv
- tests/projects.cfg
- tests/test_cli.py
- tests/test_config.py
- tests/test_project.py
- tests/test_rest.py
The ability to use a vocabulary language different from the project language was implemented in PR #600, but subsequently broken by mistake in PR #608. For example, it should be possible to use `vocab=lcsh(en)` in a project with `language=fi` where all documents are in Finnish but English language labels are used for LCSH concepts (which don't even have Finnish labels) both when reading corpora and outputting results.
This PR aims to restore that functionality by making sure that
1. When reading corpora in the directory-based format, labels are compared to vocabulary labels in the vocabulary language;
2. When performing suggest operations (CLI or REST), the labels of suggested subjects are in the vocabulary language;
3. When writing an evaluation results file which contains subject …
> Restore ability to use vocab language different from project language

- .readthedocs.yml
- annif/cli.py
- docs/commands-wiki/index.rst
- docs/conf.py
- docs/index.rst
- docs/requirements.txt
- docs/source/commands.rst
- setup.py
Switches to document Annif CLI commands on annif.readthedocs.io with automated builds instead of manually maintaining documentation in a GitHub wiki page 
Template for the page is in `docs/source/commands.rst`. 
Due to an [issue with sphinx-rtd-theme](https://github.com/readthedocs/sphinx_rtd_theme/issues/1115) (not showing bullet points in TOC lists) an older version of docutils (0.16) is used.
Edit: Also [upgrades to Click 8.1.* to allow sphinx-click to access full docstring after truncation marker `\f`
](https://github.com/NatLibFi/Annif/pull/611/commits/e830bd0f077334c8040181fd44bba00f53188e8e)
Closes #595.
> Autogenerated CLI commands documentation on ReadTheDocs

- annif/analyzer/simplemma.py
- setup.py
Fixes #617
This PR upgrades Simplemma to version 0.8.* (from 0.7.*) and removes the LRU cache, because Simplemma nowadays already has a similar cache. Thanks to @adbar for the tip!
> upgrade to simplemma 0.8 and disable unnecessary cache

- annif/cli.py
- annif/corpus/subject.py
- annif/project.py
- annif/registry.py
- annif/rest.py
- annif/vocab.py
- docs/source/commands.rst
- tests/conftest.py
- tests/test_cli.py
- tests/test_project.py
- tests/test_vocab.py
- tests/test_vocab_skos.py
This PR adds two new CLI commands, `annif load-vocab` and `annif list-vocabs`. It also deprecates the old `annif loadvoc` command. The main difference between `load-vocab` and `loadvoc` is that `load-vocab` operates directly on the vocabulary and takes a vocabulary ID as argument, while `loadvoc` takes a project ID as argument. See #602 for more details on these.
Here are examples of running the new commands:
```
$ annif load-vocab dummy tests/corpora/dummy-subjects.csv 
Loading vocabulary from CSV file tests/corpora/dummy-subjects.csv...
updating existing subject index
saving vocabulary into SKOS file data/vocabs/dummy/subjects.ttl
```
As is apparent, the `load-vocab` command is more verbose than `loadvoc` which produced little or no output.
The new `list-vocabs` command shows some basic …
> Implement load-vocab and list-vocab commands

- annif/registry.py
- tests/projects.cfg
- tests/test_vocab.py
This little PR fixes a parsing bug related to vocabulary IDs. If a vocabulary ID such as `yso-fi` or `yso-arch` was given in the configuration file, it would be shortened to `yso`. The regex for matching IDs was too restrictive.
This PR fixes the regex and adds a unit test verifying that it keeps working as intended.
> Allow use of hyphens in vocabulary IDs

- annif/backend/nn_ensemble.py
This one-line PR makes NN ensemble suggest operations silent. They used to be quiet at least in Annif 0.57, but apparently something changed in TensorFlow and now there are messages like this:
1/1 [==============================] - 0s 15ms/step 
1/1 [==============================] - 0s 15ms/step 
1/1 [==============================] - 0s 15ms/step
> fix: make NN ensemble suggest operations silent

- Dockerfile
Curl was being used for [health checks for Annif](https://github.com/NatLibFi/Annif/blob/1c815dbe8689274093fd768dd4b47f01f949595f/docker-compose-ai.finto.fi.yml#L18) instances run in the Docker Swarm / Portainer environment. Now, since the service are running in OpenShift platform, curl is no more needed in Docker image because OpenShift has internal http functionality for [health checks](https://docs.openshift.com/container-platform/4.6/applications/application-health.html).
> Remove curl from Docker image

- Dockerfile
Switching to use Poetry in Dockerfile (#605) increased the Docker image size to 3.2 GB. The image size for Annif v0.58 is 1.92 GB.
Simple fix is to just delete the cache after the installation (the `--no-cache` option of Poetry had no effect). The dependency resolution creates the `poetry.lock` file, which is used on the second round of installation (after adding Annif source code), so cache is unnecessary.
> Remove Poetry cache from Docker image

- .github/workflows/cicd.yml
The first attempt of the [test job in GH Actions failed](https://github.com/NatLibFi/Annif/actions/runs/3111298513/attempts/1) when releasing v0.59 because it took longer than the 10 min timeout limit. The run took longer than usually as for this run the Poetry cache was not available.
To avoid such problems in the future it is best to increase the timeout for both jobs.
> Increase timeout of test and publish GH Actions jobs

- annif/cli.py
- annif/rest.py
- annif/swagger/annif.yaml
- tests/test_cli.py
- tests/test_rest.py
Fixes #628
This PR implements an option `--language` / `-L` for the `annif suggest` command as well as an optional `language` parameter for the REST API `suggest` method, both of which allow overriding the language of returned subject labels.
TODO:
> Allow overriding subject label language in CLI and REST suggest operations

- .github/workflows/cicd.yml
- Dockerfile
- annif/transform/langfilter.py
- pyproject.toml
- tests/test_transform_langfilter.py
This draft PR is similar to PR #615 except it replaces the language detection previously performed using pycld3 with [Simplemma based language detection](https://github.com/adbar/simplemma/#language-detection) (by @adbar)
I intend to benchmark this against PR #615 and the current status quo (with pycld3) in the near future.
Fixes #593
> use Simplemma instead of pycld3 for language detection

- annif/parallel.py
- annif/registry.py
- tests/test_cli.py
- tests/test_parallel.py
This (draft) PR attempts to add support for the `spawn` multiprocessing mode. This is the only mode supported on Windows, and the default mode on Mac OS. The `fork` mode, supported on Linux and some other *nix systems, is more efficient because it allows loading models only once and then reusing them in forked child processes, with most of the memory shared between the processes. But `spawn` mode is still better than not being able to perform multiprocessing at all.
This PR needs more testing, ideally on both Mac OS and Windows. Currently there is just a single unit test that exercises parallel evaluation using the `spawn` mode.
Fixes #637
> add support for spawn multiprocessing mode

- annif/backend/http.py
- tests/test_backend_http.py
The http-backend uses requests library, and so the headers have now user-agent `python-requests/2.28.1`, which is shown e.g. in logs of the targeted server.
It is better to use a user-agent tailored for Annif. This PR changes the user-agent that http-backend sends in request headers to `Annif/<version>`, e.g. currently to `Annif/0.60.0.dev0`.
> Use tailored user-agent in requests by HTTP-backend

- pyproject.toml
We are currently using TensorFlow 2.9.1, which has reported vulnerabilities. Also dependabot is complaining about them.
It would be trivial to upgrade to 2.9.3, where those issues have been fixed.
But instead, I tested upgrading directly to 2.11.0. Everything seems to work fine with this new version. I also tested a small model that was trained on 2.9.1, before the upgrade, and it worked perfectly well.
I pinned this as `2.11.*` so that upgrading to patch releases is allowed in the future.
> Upgrade TensorFlow to version 2.11.*

- annif/static/css/style.css
- annif/templates/home.html
This PR adds information about a selected project to the web UI.
A button is added under the project selection:
This opens a box with the information on the project:
IMO a version with the info in a popup next to the project selection would look cleaner but I'm not sure how to implement it yet.
> Add project info to web UI

- .github/workflows/cicd.yml
As discussed in #650, this PR switches installing isort and Black from PyPI with Poetry (instead of using the GH Actions) and flake8 with Poetry, so now the versions of these tools are the same in CI/CD and in local installations (maybe depending on the Python versions in the environments; in CI/CD linting job I chose to use Python 3.10). Also this approach might be a little more secure way to install the tools as it does not rely on the GH Actions.
Downside is longer and more complex definition.
> Install linting tools with Poetry in CI/CD pipeline

- .github/workflows/cicd.yml
I noticed the following warnings in the CI/CD pipeline:
```
The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
```
They are given by the [setup-python Action](https://github.com/marketplace/actions/setup-python), and updating it should make the warnings go away.
I leave this as a draft for now, as this branch is based on the branch for #656, which should be merged first.
> Upgrade setup-python action to v4.4.0

- .github/workflows/cicd.yml
Upgrades rest of the GH Actions, continuation to #657, to get rid of the warnings in the CI/CD pipeline from Docker jobs too.
> Upgrade GitHub Actions

- annif/openapi/annif.yaml
- annif/rest.py
- tests/test_rest.py
This PR adds a resource to the root of the REST API (i.e. http://<annif_host>/v1/) that gives basic information on the API. The information given is a title for the API and the version of Annif being used. The response is a json object with the format:
```json
{
"title": "Annif REST API",
"version": "0.60.0"
}
```
Implements #655
> Add REST API root resource

- annif/backend/pav.py
- annif/backend/stwfsa.py
- annif/lexical/mllm.py
- annif/transform/inputlimiter.py
- annif/transform/langfilter.py
- pyproject.toml
- tests/test_exception.py
Black v23.1 was released recently, and as their [Stability Policy](https://black.readthedocs.io/en/stable/the_black_code_style/index.html#stability-policy) states, Black style is allowed to change between yearly/major Black releases. 
To avoid surprising failures in CI/CD, this pins the Black version.
The code style change to v23 luckily just removes a few empty lines.
> Migrate codestyle to Black v23

- CONTRIBUTING.md
- annif/backend/backend.py
- annif/backend/omikuji.py
This PR clarifies that backends only have to implement either one of `_suggest` and `_suggest_batch`, then implements batched suggest in the Omikuji backend. In practice, only the text vectorization is performed on the whole batch at once; the Omikuji implementation only supports a [predict method](https://github.com/tomtung/omikuji/blob/master/python-wrapper/omikuji/__init__.py#L106) for a single document at a time so it has to be done within a `for` loop.
There seems to be a small performance benefit. I tested this using `annif eval` the Finto AI yso-parabel-fi project/model, with the kirjaesittelyt2021/fin/test corpus. The evaluation results were unchanged, only the amount of time spent was slightly different. Memory usage remained pretty much the same.
|                 | user time | …
> Batch suggest in Omikuji backend

- annif/backend/svc.py
This PR implements `_suggest_batch` instead of single-document `_suggest` in the SVC backend, allowing the use of more efficient vector operations.
I tested this with the 20 Newsgroups data set example, as shown on the [wiki page of the SVC backend](https://github.com/NatLibFi/Annif/wiki/Backend%3A-SVC). Evaluation on the test set is 20-30% faster with the results otherwise unchanged.
There is one special case that requires attention: what to do when the input to the SVC classifier is empty or near-empty. The old `_suggest` code handled this as a special case so it short-circuits the classifier and returns an empty result. There is also a unit test that tests this (using the special input text "j" which is an unknown token and thus equivalent to empty input). The SVC model has no problem …
> Implement batched suggest in SVC backend

- annif/__init__.py
- tests/test_backend_fasttext.py
By looking at the logs from e.g. OpenShift environment it can be hard to see if Annif pod/container has booted or models are still being loaded. In error situations while Annif is in boot loop (or it seems so) it would be good to easily know from the logs if/when Annif has started.
This PR adds an info level message `finished initializing projects` to log stream for addressing the mentioned concern. For this, it was necessary to also do the [basic configuration](https://docs.python.org/dev/library/logging.html#logging.basicConfig) for the root logger and set log level to "info" (was "unset") for "annif" logger. This makes all log messages from Annif to show also the level and the logger name.
For example:
```
[2023-02-07 16:12:22 +0200] [460823] [INFO] Starting gunicorn 20.1.0
[2023-02-07 …
```
> Add log message indicating finishing projects initialization

- .github/actions/prepare/action.yml
- .github/workflows/cicd.yml
Lately the Python 3.10 test CI/CD jobs have been slow (~7 mins), because the Python dependencies have not been available from cache. First occurrence is in the [CI/CD job #308](https://github.com/NatLibFi/Annif/actions/runs/3875121566/jobs/6607220782), however it seems that the reason for the slow-down is introducing the linting job in PR #656, because this job has shared the cache keys with the Python 3.10 test job. This has prevented (re)creating/updating the cache by the test job (with the necessary optional dependencies); the "Post" steps for setup-python and caching steps in the test jobs have had errors like:
```
Failed to save: Unable to reserve cache with key setup-python-Linux-python-3.10.9-poetry-6025e512699131453ed16a5ae9a4be9139ae85329e34f47f750e6fb7af36d308, another job may …
```
> Fix slow CI/CD runs for Python 3.10

- annif/backend/ensemble.py
- annif/backend/nn_ensemble.py
- annif/suggestion.py
- annif/util.py
This adds the `_suggest_batch` method to ensemble backends. 
In all ensemble backends (simple, PAV, NN) the suggestions from the source projects are fetched by using batched suggest calls (this is on project level, so whether a backend actually uses batched suggest depends on the backend).
In case of NN ensemble the prediction (now via `_merge_hit_sets_from_sources`) is performed on the whole batch of the base suggestions in one call of the NN model. The prediction is made using the model's `__call__()` method instead of `predict()` as it is the [recommended way for "small numbers of inputs that fit in one batch"](https://www.tensorflow.org/api_docs/python/tf/keras/Model#predict) and it should offer better performance; this should also fix #674.
Also the [EnsembleOptimizer is made to use …
>  Batch suggest in ensemble backends

- .github/workflows/cicd.yml
- .github/workflows/codeql.yml
- CONTRIBUTING.md
- README.md
- docs/index.rst
Changes in:
- GH Actions 
- CI/CD workflow
- CodeQL workflow
- README.md
- CONTRIBUTING.md
- docs/index.rst (for ReadTheDocs content)
Related to #679.
> Change references to default branch: master -> main

- annif/cli.py
- annif/cli_util.py
Changes:
- [Move the helper functions & decorators to a new `cli_util.py` module](https://github.com/NatLibFi/Annif/commit/1ccb061ee94e21affe42e0da22372213dae48ee2) (as commented in https://github.com/NatLibFi/Annif/pull/663#discussion_r1095437426)
- [Use dict instead of collections.OrderedDict](https://github.com/NatLibFi/Annif/commit/c01846ac2550d06987d2519d3a0405bd3792248c)
- [Make docs-limit option a common decorator](https://github.com/NatLibFi/Annif/commit/87e42cf1c5e62947ddbdf97ae110bc1fce5208f5)
- [Add a few docstrings to helper functions](https://github.com/NatLibFi/Annif/commit/4d17c89edb53dbaa22c2fe66e05bd509a6ad512c)
- [Cosmetic fix for unnecessarily split strings](https://github.com/NatLibFi/Annif/commit/2e215ab2e991e898cb000accaf57e1a235ea4804)
- [Mark internal helper …
> Refactor and cleanup CLI module

- annif/templates/home.html
When the modification time of a project was None/null, Web UI project information section showed 1970-01-01 00:00:00.
Now "-" is displayed instead in the case of null value.
> Fix displaying of modification time for null value in Web UI project information

- .github/workflows/cicd.yml
- Dockerfile
- annif/backend/__init__.py
- pyproject.toml
- tests/test_backend.py
- tests/test_backend_stwfsa.py
> Make stwfsapy an optional dependency

- Dockerfile
Remove the duplicated fasttext entry in optional dependencies list in Dockerfile.
> Remove duplicated fasttext entry in optional dependencies list in Dockerfile

- annif/cli.py
- annif/cli_util.py
- tests/test_cli.py
Currently the output of `annif suggest` (to stdout) and `annif index` (to `document.annif` file) is e.g. as follows:
```
<http://www.yso.fi/onto/yso/p109998>	Röyttä (Ii)	0.4971785247325897
<http://www.yso.fi/onto/yso/p38304>	stabiilius (muuttumattomuus)	0.4472784399986267
<http://www.yso.fi/onto/yso/p10546>	hydrodynamiikka	0.4472784399986267
<http://www.yso.fi/onto/yso/p2048>	jääliikenne	0.44725048542022705
<http://www.yso.fi/onto/yso/p4911>	laivat	0.42701175808906555
<http://www.yso.fi/onto/yso/p12284>	hinaajat	0.40847617387771606
<http://www.yso.fi/onto/yso/p19211>	hydrostatiikka	0.3946342170238495
<http://www.yso.fi/onto/yso/p17953>	rahtilaivat	0.37881672382354736
<http://www.yso.fi/onto/yso/p16317>	höyrylaivat	0.36528536677360535
<http://www.yso.fi/onto/yso/p3976>	koneistot …
```
> Show scores in outputs of `suggest`, `eval` and `index` with 4 decimals

- .github/workflows/cicd.yml
- tests/time-startup.sh
Adds a GitHub Actions job with a shell script for measuring the CLI startup time to prevent its unnoticed deterioration.
The startup time was optimized in #696, and now it is good make sure the startup remains fast. For example, I noticed that adding type hints (planned in #690) [can slow the startup, but this can be avoided by postponing the evaluation of annotations](https://docs.python.org/3/whatsnew/3.7.html#pep-563-postponed-evaluation-of-annotations).
The timing script executes `annif --help` four times and measures user + sys time. If the average of the user + sys time is over a threshold, the job fails. The threshold is set to 0.300 s.
In the [five previous runs](https://github.com/NatLibFi/Annif/actions/runs/5022302154) the measured time was 0.245 s, 0.240 s, 0.252 s, 0.242 s and …
> Test CLI startup time with CI/CD job

- Dockerfile
Run `apt-get upgrade` in Docker build to ensure that system packages are up-to-date in the image.
> Ensure system packages are up-to-date in Docker image

- Dockerfile
`apt-get upgrade` was added in Docker build to ensure that system packages are up-to-date in the image in PR #707, but I did not add `-y` option to it, because it seemed unnecessary as the command worked while testing without it (and in this [SO post](https://askubuntu.com/questions/976080/is-y-redundant-in-apt-get-update) the `-y` was concluded to be unnecessary, but the post was about `apt-get update`!) 
However, it seems that when there is some packages to upgrade, then then the `-y` option is necessary. Without it the [build](https://github.com/NatLibFi/Annif/actions/runs/5175147366/jobs/9322461848) fails:
```#5 2.926 Reading state information...
#5 2.944 Calculating upgrade...
#5 3.091 The following packages will be upgraded:
#5 3.091   libssl1.1 openssl
#5 3.094 2 upgraded, 0 newly …
```
> Fix missing confirmation in apt-upgrade in Docker build

- .github/workflows/cicd.yml
The Docker image is good to be tested before pushing to Quay.io repository.
This PR also reorders the jobs in the GH Actions workflow, so that "publish latest Docker image" is run before "publish release".
> Add GitHub Actions job for testing Docker image

- .github/workflows/cicd.yml
- .github/workflows/docker-rebuild.yml
This is a simplified version of PR #713: instead of doing rebuilds automatically with a schedule, this just intends to use the "workflow dispatch" trigger to manually start the build.
The Docker images of "maintained" releases should be rebuild regularly for system package updates, but this can be done manually (and for Annif deployments it is probably a good idea to have manual control on when updates happen).
For now is probably enough to consider only the most recent release to be "maintained" in this sense, but [any tag (since merging this PR) can selected for rebuild](https://docs.github.com/en/actions/using-workflows/manually-running-a-workflow#running-a-workflow).
This PR adds a GH Actions workflow, which
1. checkouts the git tag of the selected release
2. builds the image and …
> Add GH Actions workflow for rebuilding the Docker image of the latest release

- annif/backend/backend.py
- annif/backend/dummy.py
- annif/backend/mllm.py
- annif/backend/nn_ensemble.py
- annif/backend/omikuji.py
- annif/backend/pav.py
- annif/backend/svc.py
- annif/backend/yake.py
- tests/test_backend_stwfsa.py
I noticed that if a STWFSA project configuration did not set the `limit` paramter, the operations based on suggest functionality (CLI commands suggest, eval, index...) were crashing:
```
echo kissa | annif suggest stwfsa-fi  
Traceback (most recent call last):
File "/home/local/jmminkin/.cache/pypoetry/virtualenvs/annif-ul-EXdhi-py3.10/bin/annif", line 6, in <module>
sys.exit(cli())
File "/home/jmminkin/.cache/pypoetry/virtualenvs/annif-ul-EXdhi-py3.10/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
return self.main(*args, **kwargs)
File "/home/jmminkin/.cache/pypoetry/virtualenvs/annif-ul-EXdhi-py3.10/lib/python3.10/site-packages/click/core.py", line 1055, in main
rv = self.invoke(ctx)
File "/home/jmminkin/.cache/pypoetry/virtualenvs/annif-ul-EXdhi-py3.10/lib/python3.1 …
```
> Fix missing limit parameter in STWFSA backend

- annif/__init__.py
- annif/backend/__init__.py
- tests/test_cli.py
Makes TF log level to be set by Annif log level using `TF_CPP_MIN_LOG_LEVEL` env variable.
Mainly used for hiding distracting TF INFO messages. Closes #720. Based on [this SO answer](https://stackoverflow.com/a/42121886).
The env setting is in the `annif/__init__.py` to make the log level change work also when TF is used by spaCy analyzer (which was not  apparent at first), in addition to TF usage by NN ensemble backend.  
I am not seeing the second message mentioned in the issue: 
2023-07-25 11:31:44.032688: I tensorflow/core/util/port.cc:104] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
I hope also this …
> Suppress TensorFlow info messages to debug level

- annif/backend/backend.py
- annif/util.py
- tests/test_project.py
If initial training of a project is not finished after any files have been created in the project's data directory, the train state and modification time information turn out incorrect (the project shows to be (fully) trained when it is not, and with a modification time). And when retraining a project is interrupted, the modification time is falsely updated.
This problem can realize more commonly when/if implementing [the `--prepare-only` option to the train command](https://github.com/NatLibFi/Annif/issues/583).
This PR makes the methods inquiring the train state and modification time to ignore files in the project's datadir with pattern `*-train*`, `tmp-*` and  `vectorizer`. The `tmp-` prefix is added to all temporary files, because some backends are using a tempfile for the model file …
> Fix train state and modification time for unfinished project training

- .readthedocs.yml
- docs/conf.py
Miscellaneous updates and tweaks for the documentation, prompted by the email from RTD:
> We are removing the "use system packages" feature on August 29th. Make sure you are installing all the required dependecies to build your project's documentation using a requirements.txt file and specifying it in your .readthedocs.yaml.
It seemed were having the setting `system_packages: true` for no reason in the configuration, so it is removed.
Also
- updates the RTD build environment to Ubuntu 22.04 and Python 3.10
- adds SWTFSA dependency to be installed to have its docstrings in the docs (forgotten from #700)
- removes pycld3 dependency (forgotten from #626)
- refines and updates the documentation page (using tips from a [blog post](https://documatt.com/blog/2021/sphinx-conf-py-tips.html))
> Updates for ReadTheDocs documentation

- tests/time-startup.sh
We have a CI test for startup time, implemented in PR #706, designed to prevent situations where basic Annif CLI commands suddenly take a long time due to e.g. slow imports.
The threshold value was set to 0.300 seconds. But nowadays this test quite often fails because the startup takes a bit longer, e.g. 0.35 seconds. I don't think anything has changed with the imports, it's just that the CI environment runs a bit slower than it used to.
This PR increases the threshold value to 0.400 seconds, which should prevent spurious test failures but still ensure that startup times have not increased dramatically.
> Increase maximum startup time threshold (0.3 -> 0.4 s)

- pyproject.toml
Register "slow" test marker as described in [pytest documentation](https://docs.pytest.org/en/stable/how-to/mark.html#registering-marks) to avoid the warning:
```
tests/test_openapi.py:22
/home/local/jmminkin/git/Annif/tests/test_openapi.py:22: PytestUnknownMarkWarning: Unknown pytest.mark.slow - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/how-to/mark.html
@pytest.mark.slow
```
The "slow" marker was added in #685.
> Avoid PytestUnknownMarkWarning due to "slow" marker 

- annif/backend/mixins.py
- annif/lexical/mllm.py
scikit-learn vectorizers used by Annif (CountVectorizer, TfidfVectorizer) trigger this warning:
UserWarning: The parameter 'token_pattern' will not be used since 'tokenizer' is not None'
This is a bit surprising, since we are not setting `token_pattern` ourselves, but its default value is not None. This PR fixes the warning by explicitly setting `token_pattern=None` whenever the `tokenizer` parameter is set in Annif calling code.
> Avoid scikit-learn UserWarning for vectorizer parameter token_pattern

- Dockerfile
[Debian Bookworm (v12.0)](https://www.debian.org/releases/bookworm/) was released 10.6.2023. It seems like a good idea to upgrade Annif's Docker image to be based on that now, before Annif 1.0 release (although the base image should not affect Annif).
> Upgrade Docker baseimage to Debian Bookworm

- annif/cli.py
- docs/source/commands.rst
When the `annif completion` command was added in #693, it was forgotten to add the command in the [CLI commands page that is shown in ReadTheDocs](https://annif.readthedocs.io/en/stable/source/commands.html) (updating that page is [only semi-automatic](https://github.com/NatLibFi/Annif/pull/611#issuecomment-1228184329)).
> Add completion command to commands list in RTD

- annif/static/css/style.css
- annif/templates/home.html
It would be nice to know which version of Annif is running for the Web UI.
This PR adds a version number string, e.g. `Annif v1.1.0` (or `Annif v1.1.0.dev0` for the development version) outside the text box in the lower right corner, see screenshot below.
An alternative position for the version number could be just below "Web UI" title in the header, but the position of this PR is the same as will be in Finto AI.
> Show Annif version in WebUI

- pyproject.toml
Fix the unit tests by switching to pin Schemathesis version only on major level. Closes #747.
> Fix tests error due to pinned schemathesis version 3.19.* / Docker rebuild

- pyproject.toml
[TensorFlow IO v0.35.0](https://github.com/tensorflow/io/releases/tag/v0.35.0) was released in December 19th. That release in PyPI does not provide many [platform wheels](https://pypi.org/project/tensorflow-io-gcs-filesystem/0.35.0/#files) that were provided by [v0.34.0](https://pypi.org/project/tensorflow-io-gcs-filesystem/0.34.0/#files). See the tracking issue https://github.com/tensorflow/io/issues/1906.
Now Annif installation with NN ensemble backend fails on Python 3.8 (there were some failed [CI runs](https://github.com/NatLibFi/Annif/actions/runs/7380737366)). 
We may want to drop support for Python 3.8 for Annif v1.1, but for the meantime, this fixes the installation by making TensorFlow IO a direct dependency for Python 3.8 and pins its version to 0.34.*.
> Fix installation on Python 3.8 due to missing Tensorflow-io wheel

- pyproject.toml
[Pytest 8.0.0 was released](https://pythontest.com/pytest/pytest-8-is-here/) on 2014-01-17. Lately Schemathesis releases have been [pinning pytest to <=8](https://github.com/schemathesis/schemathesis/blob/e088280b17b38245a00d66782f22f175a520d510/pyproject.toml#L46), and as Poetry favored pytest over Schemathesis in version resolution, pytest 8 and Schemathesis 3.14.2 (version just before pytest <=8 pinning) are now being installed. 
The problem is that tests (and thus Docker rebuild) do not work with this ancient Schemathesis version:
```
...
RuntimeError: The starlette.testclient module requires the httpx package to be installed.
You can install this with:
$ pip install httpx 
```
This is fixed by pinning to pytest 7.\*.* in Annif.
> Fix tests and Docker rebuild due to defunct Schemathesis and pytest dependencies resolution

- docs/requirements.txt
The builds for readthedocs documentation (e.g. [this](https://readthedocs.org/projects/annif/builds/23322209/)) were failing due to an error:
```
...
Sphinx version error:
The sphinxcontrib.applehelp extension used by this project needs at least Sphinx v5.0; it therefore cannot be built with this version.
```
This is fixed by upgrading dependencies used in the build.
> Fix RTD builds by upgrading dependencies 

- .github/workflows/cicd.yml
- .scrutinizer.yml
- README.md
- annif/backend/yake.py
- pyproject.toml
I started to update dependencies for the next release, but noted that many dependencies cannot be upgraded for Python 3.8, so it seems to best to drop it out the Python versions that Annif supports (after this 3.8-3.11). This is in line with the [Backward compatibility policy](https://github.com/NatLibFi/Annif/wiki/Backward-compatibility-between-Annif-releases#python-environment).
In the CI/CD pipeline the Python versions used in different actions are rotated forward.
Also removes the tensorflow-io-gcs-filesystem dependency, which was recently added in #759 to fix installing Annif on Python 3.8.
> Drop Python 3.8 support

- annif/templates/home.html
Displaying the version of Annif on Web UI was added in PR #745, but it was not working when Annif was deployed on a site using https, e.g. https://dev.annif.org: Firefox console showed error
Blocked loading mixed active content “http://dev.annif.org/v1/”
and the displayed version string was empty.
~This [SO answer](https://stackoverflow.com/a/57646910) advises to add a metatag for "[Content-Security-Policy: upgrade-insecure-requests](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy)". This "is intended for websites with large numbers of insecure legacy URLs that need to be rewritten", but I did not find another way to fix this, because the version number is queried from `/v1` path, whatever the site domain is.~
But now I started to wonder why the same …
> Fix blocked http-request for version number on https site

- annif/backend/backend.py
I noticed that after 
annif download yso-bonsai-en juhoinkinen/Annif-models-upload-testing
the modification time of omikuji projects as detected by Annif is wrong; it is shown to be the extraction time:
```
annif show-project yso-bonsai-en 
...
Modification time: 2024-03-13 11:36:22
```
This is because of the timestamp of the `data/projects/yso-bonsai-en/omikuji-model/` _directory_, which is set to the time when the files it contains get extracted.
_Originally posted by @juhoinkinen in https://github.com/NatLibFi/Annif/issues/762#issuecomment-1994122090_
---
This PR fixes the above problem by making all subdirectories in project data directory to be disregarded as model data files (the directories themselves do not affect the model results).
Also make the files in the subdirectories be …
> Fix project data files detection

- .github/dependabot.yml
Dependabot is good for keeping GH Actions up-to-date, but it has been opening one PR per Action to update (once a month), which has meant several open Dependabot PRs (currently 3). But I noticed that it is possible to make Dependabot to put all its updates to one PR, like in https://github.com/tensorflow/io/pull/1964.
See the [documentation](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#groups) of the feature.
> Group Dependabot GitHub Actions updates into one PR

- annif/registry.py
- tests/conftest.py
- tests/test_project.py
This PR makes it possible to select the projects that Annif loads on startup via a regexp pattern given in the environment variable `ANNIF_PROJECTS_INIT`.  The same env can be used in NGINX in its [location directive](https://nginx.org/en/docs/http/ngx_http_core_module.html#location) configuration to make NGINX pass a request to the Annif instance that has loaded the requested project.
An image with these changes has been running at ai.dev.finto.fi. The used helm-chart includes grouping projects with these environment variables:
yso-.*fi
yso-.*sv
yso-.*en
kauno-.*
thema-.*
ykl-.*
Closes #733.
> Allow loading selected projects using environment variable

- Dockerfile
- annif/__init__.py
- annif/cli.py
- annif/openapi/annif.yaml
- annif/openapi/validation.py
- annif/rest.py
- annif/templates/home.html
- docker-compose.yml
- docs/source/commands.rst
- pyproject.toml
- tests/conftest.py
- tests/test_cli.py
- tests/test_openapi.py
- tests/test_project.py
- tests/test_rest.py
Upgrades to Connexion 3, closes #689 and #698.
Connexion 3 introduces many changes compared to Connexion 2, see the documentation [here](https://connexion.readthedocs.io/en/stable/v3.html).
Most importantly, after the upgrade to Connexion 3, running Annif with Gunicorn requires the use Uvicorn workers; the workers can be set using the `--worker-class/-k` option of Gunicorn:
gunicorn --worker-class uvicorn.workers.UvicornWorker "annif:create_app()"
In Dockerfile there is the [enviroment variable](https://docs.gunicorn.org/en/stable/settings.html) `GUNICORN_CMD_ARGS="--worker-class uvicorn.workers.UvicornWorker"`, which gives Gunicorn the option by default, so Docker image users do not have to worry about this change.
---
The original PR discussion below beginning from first draft.
This …
> Upgrade to Connexion3

- .github/workflows/cicd.yml
- README.md
- pyproject.toml
Annif on Python 3.12 already works when the optional dependencies stwfsapy and tensorflow-cpu are not installed or even declared as dependecies.
~Closes #779.~ 
At the moment does not fully close #779 because stwfsapy and NN ensemble will not work on Python 3.12.
> Python 3.12 support

- annif/cli.py
So that tutorial for web ui (https://github.com/NatLibFi/Annif-tutorial/blob/master/transcripts/web-ui.md) can be followed for docker installations.
> Fix: Add `--host` to `annif run`

- annif/backend/http.py
- tests/test_backend_http.py
I noticed that the limit parameter in the project configuration had no effect to the number of the suggestions in the case of the HTTP backend. This is fixed by adding that parameter to the POST request, if it is used.
Also adds a test to verify that the the POST request by the HTTP backend actually contains the intended arguments.
> Fix limit parameter not passed to requests by HTTP backend

- annif/analyzer/simplemma.py
- annif/langsupport.py
- annif/simplemma_util.py
- annif/transform/langfilter.py
- pyproject.toml
- tests/test_simplemma_util.py
This PR upgrades Simplemma to the latest version 1.1.1 and adds some wrapper code to make it possible to use Simplemma language detection with a limit on the number of languages simultaneously loaded into memory. The number of languages is currently hardcoded at 5.
This will enable adding language detection functionality to the REST API in PR #659 , which has not been merged yet due to concerns about memory usage.
> Upgrade Simplemma & limit its memory usage

- annif/analyzer/simplemma.py
- annif/langsupport.py
- annif/openapi/annif.yaml
- annif/rest.py
- annif/simplemma_util.py
- annif/transform/langfilter.py
- pyproject.toml
- tests/test_openapi.py
- tests/test_rest.py
- tests/test_simplemma_util.py
This PR adds the ability to detect the language of a text to the REST API. The language detection uses the simplemma python library.
A POST method is added to the end-point `/detect-language`. It expects the request body to include a json object with the text whose language is to be detected and a list of candidate languages as their [IETF BCP 47](https://en.wikipedia.org/wiki/IETF_language_tag) ~[ISO 639-1 codes](https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes)~. For example:
```json
{
"languages": ["en", "fi"],
"text": "A quick brown fox jumped over the lazy dog."
}
```
The response is a json object with the format:
```json
{
"results": [
{"language": "en", "score": 0.85},
{"language": "fi", "score": 0.1},
{"language": null, "score": 0.1} 
]
}
```
where the scores range from 0 to …
> Add language detection to REST API

- annif/rest.py
- tests/test_rest.py
This is an improvement to the language detection REST API method (#631) which improves the implementation that was made in #659.
Results are now sorted by descending score, so the most likely language is returned first.
> Sort language detection results by descending score

- docs/source/commands.rst
Adds the necessary entry for the readthedocs documetation to include the new `detect-language` CLI command, added in #801.
Also marks REST /learn and /detect-language methods as POST like /suggest was marked.
The docs from this branch are visible [here](https://annif.readthedocs.io/en/docs-for-detect-language-cli-command/source/commands.html#other) at the moment.
> Add `detect-language` CLI command to commands list in RTD documentation

- README.md
- annif/analyzer/analyzer.py
- tests/test_analyzer.py
Based on the update-dependencies-v1.2 branch (PR #796) because it upgrades NLTK to a version that needs the `punkt_tab` package (not `punkt` anymore): https://github.com/nltk/nltk/pull/3283) 
The download is performed automatically when instantiating an Analyzer object, if the `punkt_tab` data is not found. The `README.md` has been adjusted for this (i.e. removed the instructions to run `python -m nltk.downloader punkt_tab`). NB: Adjust Wiki pages too on release.
In Dockerfile [this data download step](https://github.com/NatLibFi/Annif/blob/automate-nltkdata-download/Dockerfile#L31) is retained, so when using the Dockerimage everything is ready without download needs (otherwise the data would be re-downloaded every time Annif is used in a new container, because the NLTK data storage is …
> Automate NLTK datapackage `punkt_tab` download

- Dockerfile
Now when Python 3.12 will be fully supported (after https://github.com/NatLibFi/Annif/pull/796), lets upgrade to it in Docker image.
The upgrade should bring some performance improvements.
> Upgrade Docker baseimage to Python 3.12

- annif/cli.py
- annif/hfh_util.py
- tests/test_cli.py
- tests/test_hfh_util.py
Downloading projects from Hugging Face Hub should be done from trusted sources only. 
After this PR, if the repository hasn’t been used for downloads previously (i.e., it doesn’t appear in the Hugging Face Hub cache on local system), the `--trust-repo` option needs to be used.
> Add `--trust-repo` option to `download` CLI command

- annif/cli.py
- annif/hfh_util.py
The token was not passed to the `preupload_lfs_files()` function like it is needed for uploads when a user is not logged in with huggingface-cli.
> Fix missing Hugging Face Hub token from preupload_lfs_files() parameters

- annif/hfh_util.py
- tests/test_hfh_util.py
The project IDs and names can be of varying widths, so the fields should also be variable. The functionality is similar to the `annif list-projects` output formatting, implemented in #694.
> Make fields variable width in the projects list of Hugging Face Hub Model Card

- annif/analyzer/__init__.py
- annif/analyzer/analyzer.py
- annif/analyzer/spacy.py
- annif/analyzer/voikko.py
- tests/test_analyzer_spacy.py
- tests/test_analyzer_voikko.py
This PR fixes a problem with the initialization of optional analyzers that I noticed while working on the EstNLTK analyzer in PR #818 . For the spaCy analyzer, the code in `analyzer/__init__.py` never noticed the case when spaCy is not installed, because the `import spacy` statement only happens inside a method (due to performance reasons).
This PR adds a new static method `is_available` to all Analyzer implementations and uses that to determine whether the analyzer is available (i.e. the optional dependency is installed) or not. For spaCy and Voikko analyzers, the method is implemented by using importlib.find_spec to see if the necessary modules are available or not. This should be faster than actually importing the module, which can be done at a later time within the methods if it's …
> Smarter initialization of optional analyzers

- .github/workflows/cicd.yml
- README.md
- annif/analyzer/__init__.py
- annif/analyzer/estnltk.py
- pyproject.toml
- tests/test_analyzer_estnltk.py
This PR adds a new analyzer to support lemmatization using [EstNLTK](https://github.com/estnltk/estnltk), a natural language analysis toolkit for the Estonian language.
Note that the indirect dependencies of EstNLTK are quite large, with around ~500MB of libraries.
> EstNLTK analyzer

- annif/lexical/tokenset.py
This PR is an attempt to optimize the calculation of the ambiguity feature in MLLM. In cases of extremely many matches, the ambiguity calculation can take a long time, as reported by @RietdorfC in #822.
This PR changes the calculation so that it will first group together TokenSets with the same tokens; for example, all concepts with the same (or very similar) label can be considered together instead of calculating ambiguity for each of them separately. Due to the quadratic nature of the ambiguity calculation (it's O(N^2) where N is the number of matches found in a piece of text), reducing N by grouping TokenSets may reduce the amount of necessary comparisons quite drastically.
I'm leaving this as a draft PR because this needs to be tested further. I'm not yet 100% sure that the …
> Optimize MLLM ambiguity calculation

- README.md
- pyproject.toml
This PR upgrades the optional EstNLTK dependency from version 1.7.3 to 1.7.4. 
The functionality relevant for Annif is unaffected, but the new EstNLTK release is [now dual-licensed](https://github.com/estnltk/estnltk/issues/123#issuecomment-2612637697) (GPLv2 + Apache 2.0), which simplifies the legal situation. Thus, the License section in the top level README can be shortened, as it doesn't have to consider GPLv2 compatibility.
> Upgrade to EstNLTK 1.7.4; simplify license section in README

- annif/backend/nn_ensemble.py
- annif/util.py
- tests/test_backend_nn_ensemble.py
- tests/test_util.py
- tests/util.py
Fixes #829 
Many types of files saved by Annif using the `atomic_save()` operation had tighter permissions than expected. This is because they were first saved as temporary files, then renamed.
This PR makes sure that the file permissions respect the umask setting. The unit test verifies that this works using different commonly used umask values.
> Make sure permissions of saved files adhere to umask setting

- annif/lexical/tokenset.py
This adds a check to ensure that MLLM TokenSet objects use frozenset to store tokens. In models prior to Annif 1.3, the tokens were stored in a mutable set. The `__setstate__` method is called during unpickling and handles the conversion so that older models will still work.
We could drop this later on if compatibility with older models is no longer relevant, for example if there is another reason that they will stop working anyway.
- Related to #822 
- Post fix to #825
> Ensure compatibility with MLLM models trained using Annif 1.2 or older

- pyproject.toml
There is a [bug in Connexion 3.2.0](https://github.com/spec-first/connexion/issues/2029) affecting Swagger UI: Just after Annif startup its Swagger UI (`/v1/ui`) works, but if any other(?) API request has been made, a 500 error is thrown when trying to access it.
A workaround for now is to downgrade to Connexion ~3.1.0.
> Fix Swagger UI 500 error `Failed to load API definition.`

- annif/openapi/annif.yaml
- annif/project.py
- annif/rest.py
- annif/vocab.py
- tests/test_project.py
This PR adds information about vocabularies to the REST API, making it on par with the CLI for these aspects.
It implements the first three ideas from #837:
> - /projects/{projectId} could expose the vocabulary ID of a single project
> - /projects/ could expose the vocabulary IDs of all returned projects
> - there could be a /vocabs/ method that lists all vocabs along with basic information (similar to annif list-vocabs)
In addition to vocabulary ID, also the supported languages of the vocabulary and the current vocabulary language are exposed in the /projects and /projects/{projectId} methods. These could be useful for performing subsequent suggest calls, because they affect what languages can be requested for subject terms.
The /vocabs method returns all information about the …
> Add vocabulary information to REST API

- annif/backend/nn_ensemble.py
This one-line PR fixes a TensorFlow warning about a missing call to a superclass constructor, for example when running the test suite:
```
tests/test_backend_nn_ensemble.py::test_nn_ensemble_train_and_learn
tests/test_backend_nn_ensemble.py::test_nn_ensemble_train_cached
tests/test_backend_nn_ensemble.py::test_nn_ensemble_train_and_learn_params
/home/oisuomin/.cache/pypoetry/virtualenvs/annif-3KgT0m3n-py3.12/lib/python3.12/site-packages/keras/src/trainers/data_adapters/py_dataset_adapter.py:121: UserWarning: Your `PyDataset` class should call `super().__init__(**kwargs)` in its constructor. `**kwargs` can include `workers`, `use_multiprocessing`, `max_queue_size`. Do not pass these arguments to `fit()`, as they will be ignored.
self._warn_if_super_not_called()
```
The warning message is a …
> Add superclass constructor call to LMDBSequence, to prevent TensorFlow warning

- annif/backend/backend.py
This PR fixes a DeprecationWarning in backend/backend.py:
```
/home/oisuomin/git/Annif/annif/backend/backend.py:74: DeprecationWarning: datetime.datetime.utcfromtimestamp() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.fromtimestamp(timestamp, datetime.UTC).
datetime.utcfromtimestamp(os.path.getmtime(p))
```
The `modification_time` property has been modified to avoid the use of `datetime.utcfromtimestamp` which is going away in the future.
> Fix DeprecationWarning: avoid use of datetime.utcfromtimestamp

- .github/workflows/cicd.yml
- .scrutinizer.yml
- README.md
- pyproject.toml
Drops Annif's support for Python 3.9, rotates Python versions in CI/CD pipeline and updates Python version for Scrutinizer to 3.12.
> Drop Python 3.9 support

- annif/default_config.py
- annif/project.py
- annif/vocab/__init__.py
- annif/vocab/rules.py
- annif/vocab/subject_index.py
- tests/corpora/archaeology/extract-yso-archaeology.rq
- tests/corpora/archaeology/yso-archaeology.rdf
- tests/corpora/archaeology/yso-archaeology.ttl
- tests/projects_invalid.cfg
- tests/projects_invalid2.cfg
- tests/test_project.py
- tests/test_vocab_rules.py
This PR implements support for exclude/include rules going beyond the simple `exclude` rule that was already implemented in PR #840. The following rules are now supported:
* `exclude=*` will exclude all concepts (useful before setting include rules)
* `exclude_type=<type>` excludes all concepts of a given RDF type (can be many, separated by `|`)
* `exclude_scheme=<scheme>` excludes all concepts of a given SKOS concept scheme (can be many, separated by `|`)
* `exclude_collection=<collection>` excludes all concepts that are members of a given SKOS collection (can be many, separated by `|`)
* `include_type`, `include_scheme` and `include_collection` work the same way, but in the other direction (i.e. dropping entries from the list of excluded concepts, which means including them after they …
> Support exclude/include rules for vocabulary concepts

- annif/backend/http.py
- annif/openapi/annif.yaml
- annif/rest.py
- tests/test_backend_http.py
- tests/test_rest.py
4th part of #813, after #866.
This PR adds support for document metadata into the REST API methods `suggest`, `suggest_batch` and `learn`. It also adds metadata support to the `http` backend so that it will pass along any document metadata to the REST API call.
The `suggest` method accepts a request body of the type `application/x-www-form-urlencoded`. This is a bit old-fashioned and means that the basic data structure is a flat list of `field=value` pairs. Before this PR, there were only a few valid field names in use, including `text`, `limit` and `threshold`. I considered several alternatives on how to add support for metadata fields, which could have arbitrary names:
1. Use the metadata field directly as the field name, e.g. `title=As We May Think`
2. Use the metadata field with a …
> Flexible fusion part 4: REST API document metadata support

- annif/cli.py
- annif/corpus/document.py
- annif/corpus/json.py
- annif/corpus/types.py
- annif/schemas/document.json
- tests/test_cli.py
- tests/test_corpus.py
This PR adds a new JSON-based fulltext corpus format, based on the discussion in issue #868 (ping @RietdorfC @c-poley).
It extends the existing support for document directories. Previously, the directory had to contain `.txt` files, with gold standard subjects stored in `.tsv` (or `.key`) files with the same basename. This PR adds another option: the directory may instead (or also) contain `.json` files with JSON data of the following form:
```json
{
"text": "A quick brown fox jumped over the lazy dog.",
"metadata": {
"title": "As We May Think",
"author": "Bush, Vannevar"
},
"subjects": [
{ "uri": "http://www.yso.fi/onto/yso/p817", "label": "future" },
{ "uri": "http://www.yso.fi/onto/yso/p3295", "label": "visions (prospects)" },
{ "uri": "http://www.yso.fi/onto/yso/p15527", "label": …
```
> Add JSON fulltext corpus format

- annif/cli.py
- annif/cli_util.py
- annif/corpus/document.py
- annif/corpus/json.py
- annif/corpus/types.py
- annif/rest.py
- annif/util.py
- docs/source/commands.rst
- tests/test_cli.py
- tests/test_corpus.py
This PR adds a new `annif index-file` CLI command. It works similarly than `annif index`, but for short text corpora (in TSV, CSV or JSONL format): it processes the input corpus files one document at a time, produces subjects suggestions, and writes results in JSONL format. 
Usage examples:
- `annif index-file yso-tfidf-fi input.tsv` -> produces file `input1.annif.jsonl` with as many lines as the input file has docs
- `annif index-file yso-tfidf-fi input.csv` -> ditto
- `annif index-file yso-tfidf-fi input.jsonl` -> ditto
- `annif index-file yso-tfidf-fi input1.tsv input2.csv input3.jsonl` -> all the above in a single command, writing to three separate files
- `annif index-file --gzip yso-tfidf-fi input.tsv` -> produces gzipped file `input.annif.jsonl.gz` with as many lines as the input …
> Add annif index-file CLI command

- annif/corpus/json.py
- tests/test_cli.py
This PR fixes two recently introduced slowdowns related to JSON corpus support:
Training on JSONL documents is currently quite slow due to the JSON validation. This may be due to a recent performance issue in jsonschema: https://github.com/python-jsonschema/referencing/issues/178
Because of the slow validation, the `test_train_jsonl` unit test in `test_cli.py`, which trains a TF-IDF model on 6400 documents, is quite slow - it takes around 30 seconds on my laptop, slowing down the test suite.
This PR fixes the slow unit test by adding a `--docs-limit 100` parameter to the `annif train` command, restricting the train run and thus the slow validation to 100 documents. On my laptop, the time for running `pytest tests/test_cli.py` goes from ~45 seconds to ~15 seconds.
`import jsonschema` at …
> Fix slow annif train JSONL test & avoid slow jsonschema import

- annif/cli.py
- annif/corpus/document.py
- annif/corpus/json.py
- annif/corpus/types.py
- annif/schemas/document.json
- tests/test_cli.py
- tests/test_corpus.py
This PR adds support for an optional `document_id` field in JSON & JSONL corpus formats. It can also be used as a special field in CSV corpus files. The document_id will be stored within the Document object and retained in JSONL output produced by the new `annif index-file` command.
TODO:
Closes #885
> Support document_id in JSON(L) and CSV corpus formats & JSONL output

- .github/workflows/cicd.yml
- README.md
- pyproject.toml
When using [Poetry 2.0](https://python-poetry.org/blog/announcing-poetry-2.0.0), running any Poetry command has given a deprecation warning:
The "poetry.dev-dependencies" section is deprecated and will be removed in a future version. Use "poetry.group.dev.dependencies" instead.
and `poetry check` gives even more deprecation warnings, so I updated the `pyproject.toml` to resolve these.
I checked with  `poetry check` and [validate-pyproject tool](https://validate-pyproject.readthedocs.io/en/latest/index.html) that `pyproject.toml` should work™ with these modifcations.
I also added classifier "Development Status :: 5 - Production/Stable" and keyword "multilabel-classification" to be shown on the [Annif's PyPI project page](https://pypi.org/project/annif/).
> Upgrade to Poetry 2.0 / Resolve Poetry deprecation warnings

- annif/cli.py
Click 8.2 introduced a warning for overriding parameter name: https://github.com/pallets/click/issues/2396. Now is shown e.g. this:
```
$ annif list-projects 
/home/myuser/.cache/pypoetry/virtualenvs/annif-ul-EXdhi-py3.11/lib/python3.11/site-packages/click/core.py:1193: UserWarning: The parameter --verbosity is used more than once. Remove its duplicate as parameters should be unique.
parser = self.make_parser(ctx)
/home/myuser/.cache/pypoetry/virtualenvs/annif-ul-EXdhi-py3.11/lib/python3.11/site-packages/click/core.py:1193: UserWarning: The parameter -v is used more than once. Remove its duplicate as parameters should be unique.
parser = self.make_parser(ctx)
/home/myuser/.cache/pypoetry/virtualenvs/annif-ul-EXdhi-py3.11/lib/python3.11/site-packages/click/core.py:1186: UserWarning: The …
```
> Resolve `UserWarning: The parameter --verbosity...` for `annif list-*` CLI commands

- annif/backend/nn_ensemble.py
Reverts NatLibFi/Annif#883. 
This was a mistake: before the PR to-be-reverted, the UserWarning was shown _only_ when using models trained on some previous TensorFlow version, but after it, the UserWarning was show on all the models trained with the current TF version.
The warning has been showing on Finto AI logs all the time, I suppose for every request to NN ensemble projects. However, with this code, when running locally, the warning is only shown once after startup, which is maybe a result of the dependency updates?
Anyway, we are going to retrain NN ensemble projects for Finto AI in near future, which removes the looping log messages, if it still remains.
> Revert "Resolve `UserWarning: The structure of inputs doesn't match` by Keras"
