NatLibFi/Annif

swagger/annif.yaml

I think this speccing should be enough to start building an API for project administration using Connexion (#10), but we'll see!

Project schema for Swagger spec. Fixes #11

---

annif/backend/backend.py
annif/backend/fasttext.py
annif/backend/tfidf.py
annif/cli.py
annif/corpus/__init__.py
annif/corpus/docdir.py
annif/corpus/docfile.py
annif/corpus/subject.py
annif/project.py
annif/util.py
tests/conftest.py
tests/corpora/archaeology/documents.tsv
tests/projects.cfg
tests/test_backend.py
tests/test_backend_fasttext.py
tests/test_backend_tfidf.py
tests/test_cli.py
tests/test_project.py

Not yet ready, but I want the analysis results...

Loading train documents from TSV files. Part of #114

---

annif/backend/dummy.py
annif/backend/fasttext.py
annif/backend/http.py
annif/backend/tfidf.py
annif/hit.py
annif/util.py
tests/test_hit.py

Return hits from backends and projects as AnalysisHits instead of plain list

---

.travis.yml
annif/cli.py
annif/corpus/subject.py
annif/eval.py
tests/conftest.py
tests/test_cli.py
tests/test_eval.py

LRAP metric

---

annif/eval.py
tests/test_eval.py

reimplement NDCG metric using NumPy arrays for input

---

.scrutinizer.yml
README.md
annif/__init__.py
annif/backend/tfidf.py
annif/cli.py
annif/project.py
tests/test_cli.py

Fixes some issues found by LGTM and Scrutinizer. Tries to enable Scrutinizer code rating again.

Style fixes

---

annif/cli.py
annif/eval.py
tests/test_cli.py
tests/test_eval.py

Report number of documents in evaluate and optimize command output

---

annif/cli.py
tests/test_cli.py
tests/test_corpus.py

Remove old eval command and rename evaldir to eval

---

annif/cli.py
annif/corpus/convert.py
annif/corpus/document.py
annif/corpus/subject.py
annif/corpus/types.py
tests/test_cli.py

TSV file input for eval and optimize

---

annif/backend/__init__.py
annif/backend/ensemble.py
annif/backend/pav.py
tests/projects.cfg
tests/test_backend_pav.py

First implementation of PAV backend. No unit tests yet

---

annif/hit.py
tests/test_hit.py

Fix bug when unknown subject URIs caused invalid conversion from list to vector

---

Pipfile
setup.cfg
setup.py

Depend on connexion[swagger-ui]

---

Pipfile
setup.py

Also depend on swagger_ui_bundle

---

.travis.yml
Pipfile
annif/analyzer/__init__.py
annif/backend/__init__.py
annif/project.py
setup.py
tests/test_analyzer_voikko.py
tests/test_backend_fasttext.py
tests/test_project.py

Make fastText an optional dependency

---

annif/backend/backend.py
annif/backend/fasttext.py
annif/backend/pav.py
annif/backend/tfidf.py
annif/cli.py
annif/project.py
tests/test_backend_fasttext.py
tests/test_backend_pav.py
tests/test_backend_tfidf.py
tests/test_project.py

Done for clarity and to match CLI command name

Rename load_documents and load_corpus methods to train

---

annif/backend/fasttext.py
annif/backend/pav.py
annif/backend/vw_multi.py
annif/corpus/skos.py

unless they make use of the class parameter

Refactor: Convert classmethods to staticmethods 

---

docker-compose.yml

This with the wiki page edits close #301.

Set path to mauiservice.ini using env

---

annif/corpus/combine.py
tests/test_corpus.py

Merge subjects in CombinedCorpus instead of concatenating them

---

annif/rest.py
annif/suggestion.py

Fixes #346 caused by float32 to JSON conversion failure.

Issue346 fix web ui error float32 not json serializable

---

annif/backend/nn_ensemble.py

This fixes issue #348 where online learning didn't actually work in the nn_ensemble backend.
There were several problems related to learning in the nn_ensemble backend that had to be addressed:
* nn_ensemble is now an instance of AnnifLearningBackend
* the model is initialized before attempting to learn
* the `epochs` configuration setting is only used for initial training, not subsequent learning

Enable learning in nn_ensemble backend. Fixes #348

---

Pipfile
annif/backend/__init__.py
annif/backend/maui.py
annif/cli.py
annif/corpus/skos.py
annif/corpus/subject.py
annif/exception.py
annif/vocab.py
tests/conftest.py
tests/corpora/archaeology/yso-archaeology.ttl
tests/test_backend_fasttext.py
tests/test_backend_maui.py
tests/test_backend_pav.py
tests/test_backend_vw_multi.py
tests/test_cli.py
tests/test_project.py

Fixes #269 
This is currently WIP but already working. Unit tests need to be written and I expect that the code has to be refactored, but let's see what the QA tools say.

Add Maui Server backend

---

docker-compose.yml

Switch to [Maui Server](https://github.com/NatLibFi/MauiServer/tree/dockerization#usage-with-docker) from [Mauiservice](https://github.com/NatLibFi/mauiservice/).

Mauiserver dockerization

---

Dockerfile

Install omikuji package to Docker image to enable its usage in Docker environment.

Omikuji docker

---

annif/backend/backend.py
annif/backend/dummy.py
annif/backend/fasttext.py
annif/backend/mixins.py
annif/backend/nn_ensemble.py
annif/backend/omikuji.py
annif/backend/pav.py
annif/backend/vw_multi.py
annif/eval.py
annif/templates/home.html
tests/test_backend_nn_ensemble.py
tests/test_backend_omikuji.py
tests/test_backend_vw_multi.py
tests/test_cli.py
tests/test_exception.py
tests/test_project.py

This PR fixes many code quality problems flagged by SonarQube.

Fix sonarqube errors

---

annif/backend/dummy.py
annif/backend/fasttext.py
annif/backend/http.py
annif/backend/maui.py
annif/backend/omikuji.py
annif/backend/pav.py
annif/cli.py
annif/corpus/skos.py
annif/corpus/subject.py
annif/corpus/types.py
annif/suggestion.py
annif/swagger/annif.yaml
annif/vocab.py
tests/test_backend_http.py
tests/test_backend_maui.py
tests/test_cli.py
tests/test_eval.py
tests/test_rest.py
tests/test_suggestion.py
tests/test_vocab.py
tests/test_vocab_skos.py
tests/test_vocab_tsv.py

This closes #157. 
~This overlaps with #383, and for now I made a new temporary branch from this, where #383 is merged.~

Issue157 support for notation codes

---

annif/backend/maui.py
annif/backend/omikuji.py
tests/test_backend_maui.py
tests/test_backend_omikuji.py

Issue395 Maui and Omikuji suggest with empty input 

---

annif/backend/fasttext.py

Don't attempt to merge similar documents when creating fasttext train file

---

README.md

Would this do as the new header using the logo?

Update README.md; add Annif logo

---

annif/backend/ensemble.py
annif/backend/hyperopt.py
annif/backend/nn_ensemble.py
annif/backend/pav.py
annif/cli.py
annif/corpus/subject.py
annif/eval.py
annif/parallel.py
annif/project.py
setup.py
tests/test_backend_ensemble.py
tests/test_cli.py
tests/test_parallel.py

Fixes #321
This is very rough and there are no unit tests yet, but creating a draft PR to get some feedback from QA tools.

Implement hyperparameter optimization of ensemble weights

---

www/accessibility.html
www/index.html

The link to the statement is in an own section below "Publications" section:

Add accessibility statement

---

annif/backend/nn_ensemble.py

Fixes #443
Since the LMDB is closed before starting the TensorFlow model training, it doesn't matter if the training gets aborted. The LMDB can still be reused for another training run.
I'd appreciate if you could test this @mo-fu but I understand if you don't have time

Commit transaction and reopen LMDB read-only for NN ensemble training

---

annif/analyzer/__init__.py
annif/analyzer/analyzer.py
annif/analyzer/simple.py
annif/analyzer/snowball.py
annif/analyzer/voikko.py
tests/test_analyzer.py
tests/test_backend_omikuji.py

The changes in this PR will decrease the min token size for the analyzer to two. As discussed in #456 the impact on run time is not very large.

Set Min Token Size to Two

---

annif/backend/mllm.py
tests/test_backend_mllm.py

Fixes #484
Creating a draft PR to get feedback from QA tools.

Show error when training MLLM on empty corpus

---

annif/backend/mllm.py
annif/lexical/mllm.py
annif/parallel.py

Fixes #483 
Early draft, opening to get feedback from QA tools.
Still needs more testing & refinement

Process training docs in parallel in MLLM backend

---

CITATION.cff
README.md
setup.cfg

Suggestion for a citation file for Annif repo. Feel free to add / edit things. (Fix #542)

Add CITATION.cff file

---

annif/corpus/subject.py
annif/util.py

When a project's vocabulary is not up-to-date with the corpus being used there can be very many warnings like `warning: Unknown subject URI <http://www.yso.fi/onto/yso/p22036>` that flood the screen. 
<details>
<summary>See an example output</summary>
annif train tfidf-en ../Annif-tutorial/data-sets/yso-nlf/docs/train/
Backend tfidf: transforming subject corpus
Backend tfidf: creating vectorizer
warning: Unknown subject URI <http://www.yso.fi/onto/yso/p5843>
warning: Unknown subject URI <http://www.yso.fi/onto/yso/p20828>
warning: Unknown subject URI <http://www.yso.fi/onto/yso/p8927>
warning: Unknown subject URI <http://www.yso.fi/onto/yso/p649>
warning: Unknown subject URI <http://www.yso.fi/onto/yso/p2434>
warning: Unknown subject URI <http://www.yso.fi/onto/yso/p7227>
warning: Unknown …

Suppress duplicate log messages from subject module

---

www/accessibility.html

Update accessibility.html again

---

.github/workflows/cicd.yml
README.md
pyproject.toml

Adds support for Python 3.13.
Closes #850.

Support Python 3.13
